<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php //if ($block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <?php if (!$rating) $rating =0; ?>
    <div class="rating-summary">
         <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
         <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $rating; ?>%">
             <span style="width:<?php /* @escapeNotVerified */ echo $rating; ?>%"><span><span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $rating; ?></span>% of <span itemprop="bestRating">100</span></span></span>
         </div>
     </div>
    <div class="reviews-actions">
        <a class="action view" href="<?php /* @escapeNotVerified */ echo $urlForm ?>"><span itemprop="reviewCount"><?php /* @escapeNotVerified */ echo($block->getReviewsCount()) ? $block->getReviewsCount() : '0';?></span>&nbsp;<span><?php /* @escapeNotVerified */ echo($block->getReviewsCount() == 1 || !$block->getReviewsCount()) ? __('Review') : __('Reviews') ?></span></a>
    </div>
</div>

