<?php
/**
 * Copyright © 2016  (magetop99@gmail.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * 
 */
?>
<?php
/**
 * Blog available for import template
 *
 * @var $block \Magento\Backend\Block\Template
 */
?>

<table class="available-imports">
	<tr>
		<td class="item">
			<table>
				<tr>
					<td>
						<div class="itm-hld" onclick="window.location='<?php echo $block->getUrl('blog/import/wordpress') ?>'">
							<img class="img" src="<?php echo $this->getViewFileUrl('Magetop_Blog::images/wordpress.png') ?>" />
							<span class="lable">Import from WordPress (beta)</span>
						</div>
					</td>
					<td></td>
					<td></td>
					<td></td>
				<tr>
			</table>
		</td>
		<td class="item">
			<table>
				<tr>
					<td>
						<div class="itm-hld" onclick="window.open('http://magetop.com/contact/')">
							<h2 class="img more">Need More?<br/><br/>Other CMS or Extension</h2>
							<span class="lable">Contact Magetop Team<br/><br/></span>
						</div>
					</td>
					<td></td>
					<td></td>
					<td></td>
				<tr>
			</table>
		</td>
		<td class="item"></td>
		<td class="item"></td>
	</tr>
</table>
