<!--
/**
 * @author      Magetop Developer (Kien)
 * @package     Magento Multi Vendor Marketplace_Seller_Store_Pickup
 * @copyright   Copyright (c) Magetop (https://www.magetop.com)
 * @terms       https://www.magetop.com/terms
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 **/
-->
<?php 
    $storepickupData = $block->getCollection()->getData(); 
    if(!$storepickupData){
        $storepickupData['id'] = ''; 
        $storepickupData['title'] = '';
        $storepickupData['status'] = 1; 
        $storepickupData['longitude'] = 11.154128700000001; 
        $storepickupData['latitude'] = 48.810876847030585; 
        $storepickupData['zoom_level'] = 2; 
        $storepickupData['shop_location'] = ''; 
    }
?>
<div class="block content-storepickup mgt-theme-div">
    <form id="storepickup-form" action="<?php echo $block->getUrl('sellerstorepickup/index/save') ?>" method="post" novalidate="novalidate" enctype="multipart/form-data">
        <legend class="legend">
            <span><?php echo __('Store Pickup Information') ?></span>
            <div class="primary" style="float: right;">
                <button type="submit" class="action continue primary" title="<?php echo __('Continue') ?>"><span><?php echo __('Save') ?></span></button>
            </div>
        </legend>
        <fieldset class="fieldset info storepickup">
            <input type="hidden" value="<?php echo $storepickupData['id'] ?>" name="id"/>
            <div class="field field-title required">
                <label class="label" for="title">
                    <span><?php echo __('Store Name') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_title" value="<?php echo $storepickupData['title'] ?>" type="text" aria-required="true" name="title" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field field-phone_number required">
                <label class="label" for="phone_number">
                    <span><?php echo __('Contact Number') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_phone_number" value="<?php echo $storepickupData['phone_number'] ?>" type="text" aria-required="true" name="phone_number" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field field-mapicon">
                <label class="label" for="mapicon">
                    <span><?php echo __('Image') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_mapicon" value="<?php echo $storepickupData['mapicon'] ?>" type="file" aria-required="true" name="mapicon" class="input-text"/>
                    <?php if($storepickupData['mapicon']){ 
						$_urlImage = $block->getUrlImage($storepickupData['mapicon']);
					?>
    					<div class="block block-image" style="width: 150px;margin-top: 10px;">
    						<img src="<?php echo $_urlImage ?>" title="" alt="" /><br />
    						<input type="checkbox" id="mapicon_delete" value="1" name="mapicon[delete]" />
    						<label class="label" for="mapicon_delete"><?php /* @escapeNotVerified */ echo __('Delete Image') ?></label>
    						<input type="hidden" name="mapicon[value]" value="<?php echo $storepickupData['mapicon'] ?>" />
    					</div>
					<?php } ?>
                </div>
            </div> 
            <div class="field field-status required">
                <label class="label" for="status">
                    <span><?php echo __('Status') ?></span>
                </label>
                <div class="control">
                    <select  name="status">
                        <option <?php echo $storepickupData['status']==1?'selected':'' ?> value="1"><?php echo __('Enable') ?></option>
                        <option <?php echo $storepickupData['status']==0?'selected':'' ?> value="0"><?php echo __('Disable') ?></option>
                    </select>
                </div>
            </div>
        </fieldset>
        <!--------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
        <legend class="legend">
            <span><?php echo __('Store Address') ?></span>
        </legend>
        <fieldset class="fieldset info storepickup">
            <div class="field field-address required">
                <label class="label" for="address">
                    <span><?php echo __('Street Address') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_address" value="<?php echo $storepickupData['address'] ?>" type="text" aria-required="true" name="address" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field field-city required">
                <label class="label" for="city">
                    <span><?php echo __('City') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_city" value="<?php echo $storepickupData['city'] ?>" type="text" aria-required="true" name="city" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field field-country required">
                <label class="label" for="country">
                    <span><?php echo __('Country') ?></span>
                </label>
                <div class="control">
                    <!--<input id="sellerstorepickup_country" value="<?php echo $storepickupData['country'] ?>" type="text" aria-required="true" name="country" class="input-text required-entry" data-validate="{required:true}"/>-->
                    <select id="sellerstorepickup_country" name="country" title="<?php /* @escapeNotVerified */ echo __('Country') ?>">
                        <?php
                            $_countries = \Magento\Framework\App\ObjectManager::getInstance()->create('Magento\Directory\Model\Config\Source\Country')->toOptionArray();
                            foreach($_countries as $k=>$_countryitem) {
                    	?>
                                <option value="<?php echo $_countryitem['value']?>" <?php echo $_countryitem['value'] == $storepickupData['country']?'selected="selected"':'' ?>><?php echo $_countryitem['label']?></option>
                        <?php
                    		}
                        ?>
                    </select> 
                </div>
            </div>
            <div class="field field-state required">
                <label class="label" for="state">
                    <span><?php echo __('State/Province') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_state" value="<?php echo $storepickupData['state'] ?>" type="text" aria-required="true" name="state" class="input-text required-entry" data-validate="{required:true}"/>
                    <script type="text/javascript">
                    require([
                        'jquery',
                        'mage/template',
                        'jquery/ui',
                        'mage/translate'
                    ],
                    function($, mageTemplate) {
                        var regionJson = <?php echo $this->helper('Magetop\Marketplace\Helper\Data')->JsonEncode(\Magento\Framework\App\ObjectManager::getInstance()->create('\Magento\Directory\Helper\Data')->getRegionData()); ?>;
                        if(regionJson[$('#sellerstorepickup_country').val()]){
                            $('#sellerstorepickup_state').replaceWith("<select id='sellerstorepickup_state' name='state' title='State/Province'><option value=''>--Please Select--</option></select>");
                            $.each(regionJson[$('#sellerstorepickup_country').val()], function(key, value) {
                                if(key == '<?php echo $storepickupData['state'] ?>'){
                                    $('#sellerstorepickup_state').append('<option title="'+value.name+'" data-region-code="'+value.code+'" value="'+key+'" selected="selected">'+value.name+'</option>');   
                                }else{
                                    $('#sellerstorepickup_state').append('<option title="'+value.name+'" data-region-code="'+value.code+'" value="'+key+'">'+value.name+'</option>');  
                                }                            
                            });
                        };                       
                        $('#sellerstorepickup_country').on('change', function(event){
                            if(regionJson[$(this).val()]){
                                $('#sellerstorepickup_state').replaceWith("<select id='sellerstorepickup_state' name='state' title='State/Province'><option value=''>--Please Select--</option></select>");
                                $.each(regionJson[$(this).val()], function(key, value) {
                                    $('#sellerstorepickup_state').append('<option title="'+value.name+'" data-region-code="'+value.code+'" value="'+key+'">'+value.name+'</option>');                                        
                                });
                            }else{
                                $('#sellerstorepickup_state').replaceWith('<input class="input-text" type="text" name="state" id="sellerstorepickup_state"/>');
                            }
                        });
                    });
                </script>
                </div>
            </div>
            <div class="field field-zipcode required">
                <label class="label" for="zipcode">
                    <span><?php echo __('Zip/Postal Code') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_zipcode" value="<?php echo $storepickupData['zipcode'] ?>" type="text" aria-required="true" name="zipcode" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
        </fieldset>
        <!--------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
        <legend class="legend">
            <span><?php echo __('Store Times (In 24 Hour Time Format)') ?></span>
        </legend>
        <fieldset class="fieldset info storepickup">
            <?php $store_time = json_decode($storepickupData['store_time']) ?>
            <?php for($day = 2;$day<=8;$day++){ ?>
                <div class="field required">
                    <label class="label">
                        <span>
                            <?php 
                                switch($day){
                                    case 2 : 
                                        echo __('Monday');
                                        $text_day = 'mon';
                                        $open_day = $store_time->mon_in_time;
                                        $close_day = $store_time->mon_out_time;
                                    break;
                                    case 3 : 
                                        echo __('Tuesday');
                                        $text_day = 'tue';
                                        $open_day = $store_time->tue_in_time;
                                        $close_day = $store_time->tue_out_time;
                                    break;
                                    case 4 : 
                                        echo __('Wednesday');
                                        $text_day = 'web';
                                        $open_day = $store_time->web_in_time;
                                        $close_day = $store_time->web_out_time;
                                    break;
                                    case 5 : 
                                        echo __('Thursday');
                                        $text_day = 'thu';
                                        $open_day = $store_time->thu_in_time;
                                        $close_day = $store_time->thu_out_time;
                                    break;
                                    case 6 : 
                                        echo __('Friday');
                                        $text_day = 'fri';
                                        $open_day = $store_time->fri_in_time;
                                        $close_day = $store_time->fri_out_time;
                                    break;
                                    case 7 : 
                                        echo __('Saturday');
                                        $text_day = 'sat';
                                        $open_day = $store_time->sat_in_time;
                                        $close_day = $store_time->sat_out_time;
                                    break;
                                    case 8 : 
                                        echo __('Sunday');
                                        $text_day = 'sun';
                                        $open_day = $store_time->sun_in_time;
                                        $close_day = $store_time->sun_out_time;
                                    break;
                                }
                            ?>
                        </span>
                    </label>
                    <div class="field field-day required">
                        <div class="control">
        					<select name="store_time[<?php echo $text_day ?>_in_time][]" style="width: 10%">
                                <?php 
                                    for($i=0;$i<24;$i++){
                                        if($i<10){
                                ?>
                                            <option <?php echo $open_day['0']=='0'.$i?'selected':'' ?> value='0<?php echo $i ?>'>0<?php echo $i ?></option>
                                <?php
                                        }else{
                                ?>
                                            <option <?php echo $open_day['0']==$i?'selected':'' ?> value='<?php echo $i ?>'><?php echo $i ?></option>
                                <?php
                                        }
                                    } 
                                ?>
                            </select> :
        					<select name="store_time[<?php echo $text_day ?>_in_time][]" style="width: 10%">
                                <?php 
                                    for($i=0;$i<60;$i++){
                                        if($i<10){
                                ?>
                                            <option <?php echo $open_day['1']=='0'.$i?'selected':'' ?> value='0<?php echo $i ?>'>0<?php echo $i ?></option>
                                <?php
                                        }else{
                                ?>
                                            <option <?php echo $open_day['1']==$i?'selected':'' ?> value='<?php echo $i ?>'><?php echo $i ?></option>
                                <?php
                                        }
                                    } 
                                ?>
                            </select> :
        					<select name="store_time[<?php echo $text_day ?>_in_time][]" style="width: 10%">
                                <?php 
                                    for($i=0;$i<60;$i++){
                                        if($i<10){
                                ?>
                                            <option <?php echo $open_day['2']=='0'.$i?'selected':'' ?> value='0<?php echo $i ?>'>0<?php echo $i ?></option>
                                <?php
                                        }else{
                                ?>
                                            <option <?php echo $open_day['2']==$i?'selected':'' ?> value='<?php echo $i ?>'><?php echo $i ?></option>
                                <?php
                                        }
                                    } 
                                ?>
                            </select>
                            <span style="margin: 0px 20px;"><?php echo __('To') ?></span>
                            <select name="store_time[<?php echo $text_day ?>_out_time][]" style="width: 10%">
                                <?php 
                                    for($i=0;$i<24;$i++){
                                        if($i<10){
                                ?>
                                            <option <?php echo $close_day['0']=='0'.$i?'selected':'' ?> value='0<?php echo $i ?>'>0<?php echo $i ?></option>
                                <?php
                                        }else{
                                ?>
                                            <option <?php echo $close_day['0']==$i?'selected':'' ?> value='<?php echo $i ?>'><?php echo $i ?></option>
                                <?php
                                        }
                                    } 
                                ?>
                            </select> :
        					<select name="store_time[<?php echo $text_day ?>_out_time][]" style="width: 10%">
                                <?php 
                                    for($i=0;$i<60;$i++){
                                        if($i<10){
                                ?>
                                            <option <?php echo $close_day['1']=='0'.$i?'selected':'' ?> value='0<?php echo $i ?>'>0<?php echo $i ?></option>
                                <?php
                                        }else{
                                ?>
                                            <option <?php echo $close_day['1']==$i?'selected':'' ?> value='<?php echo $i ?>'><?php echo $i ?></option>
                                <?php
                                        }
                                    } 
                                ?>
                            </select> :
        					<select name="store_time[<?php echo $text_day ?>_out_time][]" style="width: 10%">
                                <?php 
                                    for($i=0;$i<60;$i++){
                                        if($i<10){
                                ?>
                                            <option <?php echo $close_day['2']=='0'.$i?'selected':'' ?> value='0<?php echo $i ?>'>0<?php echo $i ?></option>
                                <?php
                                        }else{
                                ?>
                                            <option <?php echo $close_day['2']==$i?'selected':'' ?> value='<?php echo $i ?>'><?php echo $i ?></option>
                                <?php
                                        }
                                    } 
                                ?>
                            </select>                                        
        				</div>
                    </div>
                </div>
            <?php } ?>
        </fieldset>
        <!--------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
        <legend class="legend">
            <span><?php echo __('Store Map') ?></span>
        </legend>
        <fieldset class="fieldset info storepickup">
            <div class="field field-location required">
                <label class="label" for="location">
                    <span><?php echo __('Store Location') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_shop_location" value="<?php echo $storepickupData['shop_location'] ?>" type="text" aria-required="true" name="shop_location" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div> 
            <div class="field field-longitude required">
                <label class="label" for="longitude">
                    <span><?php echo __('Longitude') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_longitude" value="<?php echo $storepickupData['longitude'] ?>" type="text" aria-required="true" name="longitude" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field field-latitude required">
                <label class="label" for="latitude">
                    <span><?php echo __('Latitude') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_latitude" value="<?php echo $storepickupData['latitude'] ?>" type="text" aria-required="true" name="latitude" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field field-zoom_level required">
                <label class="label" for="zoom_level">
                    <span><?php echo __('Zoom Level') ?></span>
                </label>
                <div class="control">
                    <input id="sellerstorepickup_zoom_level" value="<?php echo $storepickupData['zoom_level'] ?>" type="text" aria-required="true" name="zoom_level" class="input-text required-entry" data-validate="{required:true}"/>
                </div>
            </div>  
            <div class="google-map" id="google-map">
                <div id="button-reset" style="margin-top:20px; margin-bottom: -12px;">
                    <button type="button">
                        <span><?php echo __('Reset Google Map')?></span>
                    </button>
                </div>        
                <div id="notice-map"></div>        
                <div id="googleMap" style="height: 300px;width: 100%;margin-top: 20px;border: 1px solid;"></div>
            </div>
			<?php 
				$_mkhelp = $this->helper('Magetop\Marketplace\Helper\Data');
				$_mapkey =  $_mkhelp->getKeyMap();
			?>
            <?php if( isset($_SERVER['HTTPS'] ) ) { ?>
                <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3&key=<?php echo $_mapkey; ?>&libraries=places&sensor=false"></script>
            <?php }else{ ?>
                <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&key=<?php echo $_mapkey; ?>&libraries=places&sensor=false"></script>
            <?php } ?>
            <script type="text/javascript">
            	require([
            		'jquery',
            		'Magento_Ui/js/modal/modal',
            		'mk_seller_store_pickup_map_seller_js'
            	],
            	function($, modal, mkMap) {
                    var lat = <?php echo $storepickupData['latitude'] ?>;
                    var lon = <?php echo $storepickupData['longitude'] ?>;
                    var zoom_level = <?php echo $storepickupData['zoom_level'] ?>;
                    var shop_location = '<?php echo $storepickupData['shop_location'] ?>';
                    
                    loadMap = new mkMap();
                    loadMap.getSellerStorePickupPoint(lat,lon,zoom_level);
                    
                    $('#button-reset').click(function(){
                        loadMap.getSellerStorePickupPoint(lat,lon,zoom_level);
                        $('#sellerstorepickup_latitude').val(lat);
                        $('#sellerstorepickup_longitude').val(lon);
                        $('#sellerstorepickup_zoom_level').val(zoom_level);
                        $('#sellerstorepickup_shop_location').val(shop_location);
                        $('#sellerstorepickup_latitude').css('background','#FFFFFF');
                        $('#sellerstorepickup_longitude').css('background','#FFFFFF');
                        $('#sellerstorepickup_zoom_level').css('background','#FFFFFF');
                        $('#sellerstorepickup_shop_location').css('background','#FFFFFF');
                        console.log('reset map');
                    });
                });
            </script> 
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action continue primary" title="<?php echo __('Continue') ?>"><span><?php echo __('Save') ?></span></button>
            </div>
            <div style="float: right;" class="primary">
                <a href="javascript:;" onclick="javascript: window.history.back();" class="left"><?php echo __('Back') ?></a>
            </div>
        </div>
    </form>
</div>
<script>
    require([
        "jquery",
        'Magento_Ui/js/modal/confirm',
        'Magento_Ui/js/modal/alert',
        "mage/calendar"
    ], function($,confirmation,alert){
        $('.seller_storepickup').addClass('current');
    });
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#storepickup-form');
        dataForm.mage('validation', {});
        var _action = dataForm.attr('action');
    });
</script>