<?php $product = $block->getProduct();  ?>
<?php $helper = $this->helper("Magehq\BuyNow\Helper\Data"); ?>
<?php $buttonTitle = $helper->getConfig('buynow/general/button_title');?>
<?php 
if($helper->getConfig('buynow/general/enable')) {
if ($product->isSaleable()) : ?>
    <?php $postParams = $block->getAddToCartPostParams($product); ?>
    <div class="buynow-btn">
        <form action="<?php /* @noEscape */ echo $postParams['action']; ?>"
              id="product_addtocart_form_<?php /* @noEscape */ echo $postParams['data']['product']; ?>"
              method="post">
              
            <input type="hidden" 
                   name="product"
                   value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
            <input type="hidden"
                   name="<?php /* @noEscape */ echo 'uenc'; ?>"
                   value="<?php /* @noEscape */ echo $postParams['data']['uenc']; ?>">
            <?php echo $block->getBlockHtml('formkey')?>
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__($buttonTitle)); ?>"
                    class="action tocart buynow primary"
                    data-mage-init='
                    {
                        "Magehq_BuyNow/js/buy-now": {
                            "form": "#product_addtocart_form_<?php echo $postParams['data']['product']; ?>"
                        }
                    }
                '>
                <span><?php /* @noEscape */ echo __($buttonTitle) ?></span>
            </button>
        </form>
    </div>
<?php endif; ?>
<style type="text/css">
  <?php if($helper->getConfig('buynow/general/hide_add_to_cart')) { ?>
  .product-item-actions .actions-primary .tocart {
    display: none;
  }
  <?php } ?>
</style>
<?php } ?>