<?php $helper = $this->helper("Magehq\BuyNow\Helper\Data"); ?>
<?php $addtocartId = $helper->getConfig('buynow/general/addtocart_id'); ?>
<?php $buttonTitle = $helper->getConfig('buynow/general/button_title'); ?>
<?php $formId = $addtocartId ? $addtocartId : "product_addtocart_form"; 
if($helper->getConfig('buynow/general/enable')) { ?>
<!-- <div class="buynow-button"> -->
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="buynow primary tocart" data-mage-init='
    {
        "Magehq_BuyNow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '>
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
<!-- </div> -->
<style type="text/css">
	<?php if($helper->getConfig('buynow/general/hide_add_to_cart')) { ?>
	#product-addtocart-button {
		display: none;
	}
	<?php } ?>
</style>
<?php } ?>