<?php /** * Copyright © 2016 (magetop99@gmail.com). All rights reserved. * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php). * * */ ?> <?php /** * Blog post js template * * @var $block \Magento\Framework\View\Element\Template */ ?> <script type="text/javascript">var addthis_config = {"data_track_clickback":false};</script><script type="text/javascript" async src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54d0e08f04bdcb21"></script><script type="text/javascript">
    var addthis_config = {
        ui_language: "en"
    }</script>