<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
<div class="block pro-list-block">
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="tabslide-content">    
		<div class="products-grid products-<?php /* @escapeNotVerified */ echo $type; ?> owl-carousel">
                <?php foreach ($items as $_item): ?>
                <div class="item">
					<?php 
						$_themeHelper = $this->helper('Magetop\Themes\Helper\Data'); 
						echo $_themeHelper->getLabels($_product);
					?>
					<div class="product-top product-img">
						<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-image">
							<?php echo $block->getImage($_item, $image)->toHtml(); ?>
						</a>
						<?php if ($showAddTo): ?>
							<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
								<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
									<?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
								<?php endif; ?>
							</div>
						<?php endif; ?>
					</div>
					<div class="product-des">
						<h2 class="product-name">
							<a title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
								<?php echo $block->escapeHtml($_item->getName()) ?>
							</a>
						</h2>
						<?php if ($templateType): ?>
							<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
						<?php endif; ?>
						<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
						<?php if ($showAddTo || $showCart): ?>
							<div class="product actions product-item-actions">
								<?php if ($showCart): ?>
									<div class="actions-primary">
										<?php if ($_item->isSaleable()): ?>
											<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
												<button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												?>
												<button class="action tocart primary"
													data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
													type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php endif; ?>
										<?php else: ?>
											<?php if ($_item->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								<?php endif; ?>                     
							</div>
						<?php endif; ?>
					</div>
                </div>
                <?php endforeach ?>
        </div>
	</div>	
</div>
<script type="text/javascript">
    require(["jquery","magetop/owlcarousel"], function($){
        jQuery(document).ready(function($){
			$('.products-<?php /* @escapeNotVerified */ echo $type; ?>').owlCarousel({
				slideSpeed:  300,						
				nav:true,
				dots: false,
				responsiveClass:true,				
				responsive:{
							0:{
								margin:10,
								items:2
								
							},
							600:{
								margin:10,
								items:3
							},
							1000:{
								margin:20,
								items:5
							}
						}
			});
		});
    });
</script>
<?php endif;?>
