<!--
/**
 * @author      Magetop Developer (Kien)
 * @package     Magento Multi Vendor Marketplace_Seller_Membership
 * @copyright   Copyright (c) Magetop (https://www.magetop.com)
 * @terms       https://www.magetop.com/terms
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 **/
-->
<?php
    use Magento\Framework\App\Action\Action;
    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
<div class="message info empty">
    <div><?php echo __('We can\'t find products matching the selection.') ?></div>
</div>
<?php else: ?>
<div class="mk-newest-products">
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    		if ($block->getMode() == 'grid') {
    			$viewMode = 'grid';
    			$image = 'category_page_grid';
    			$showDescription = false;
    			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    		} else {
    			$viewMode = 'list';
    			$image = 'category_page_list';
    			$showDescription = true;
    			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    		}
    		$pos = $block->getPositioned();
		?>
    <div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php foreach ($_productCollection as $_product): ?>
            <?php echo($iterator++ == 1) ? '<li class="item product product-item" style="width: 23%;">' : '</li><li class="item product product-item" style="width: 23%;">' ?>
            <div class="product-item-info" data-container="product-grid" style="width: 90%;">
                <?php
    						$productImage = $block->getImage($_product, $image);
    						if ($pos != null) {
    							$position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
    						}
						?>
                <?php echo $productImage->toHtml(); ?>
                <div class="product details product-item-details">
                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                    <strong class="product name product-item-name" style="font-size:23px">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                    </strong>
                    <div class="detail_membership" style="font-size: 11px">
                        <div class="membership_time">
                            <?php echo 'Time: '.$_product->getTime().' Days'; ?>
                        </div>
                        <div class="membership_number">
                            <?php echo 'Number product upload each month: '.$_product->getNumber(); ?>
                        </div>
                        <div class="membership_commission">
                            <?php echo 'Commission: '.$_product->getCommission().'%'; ?>
                        </div>
                        <div class="membership_price">
                            <span>
                                <strong>
                                    <?php echo 'Price: '.\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\Pricing\Helper\Data')->currency(@number_format($_product->getPrice(),2),true,false); ?>
                                </strong>
                            </span>
                        </div>
                    </div>

                    <?php //echo $block->getProductPrice($_product) ?>
                    <?php //echo $block->getProductDetailsHtml($_product); ?>

                    <div class="product-item-inner">
                        <div class="product actions product-item-actions"
                            <?php echo @strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                            <div class="actions-primary"
                                <?php echo @strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>"
                                    method="post">
                                    <input type="hidden" name="product"
                                        value="<?php echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                        value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                        class="action tocart primary" style="margin-top: 20px">
                                        <span><?php echo __('Add to Cart') ?></span>
                                    </button>
                                </form>
                                <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                <?php else: ?>
                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ($showDescription):?>
                        <div class="product description product-item-description">
                            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?php echo $_product->getProductUrl() ?>"
                                title="<?php echo $_productNameStripped ?>" class="action more">
                                <?php echo __('Learn More') ?>
                            </a>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
</div>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
			"[data-role=tocart-form], .form.map.checkout": {
				"catalogAddToCart": {}
			}
		}
		</script>
<?php endif; ?>
<?php endif; ?>
<script>
require(['jquery', 'mage/mage'], function($) {
    $('.toolbar-products').css('position', 'unset');
})
</script>