<?php
/**
 * Copyright © 2015  (magetop99@gmail.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * 
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Magetop\Blog\Block\Sidebar\Archive
 */
?>

<?php
	$_months = $block->getMonths();
?>
<?php if (count($_months)) { ?>
<div class="widget block block-blog" data-bind="scope: 'blog-archive'">
    <div class="menu-archive">
        <h4><?php echo __('Archive') ?></h4>
    	<ul>
			<?php foreach ($_months as $time) { ?>
				<?php
					$title = $block->getMonth($time).' '.$block->getYear($time);
					$title = $block->escapeHtml($title, null, true);
				?>
				<li>
					<a title="<?php echo __('Archive %s', $title) ?>" class="archive-item-link" href="<?php echo $block->getTimeUrl($time) ?>">
						<?php echo $title; ?>
					</a>
				</li>

			<?php } ?>
		</ul>
    </div>
</div>
<?php } ?>