<?php
/**
 * Copyright © 2015  (magetop99@gmail.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * 
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Magetop\Blog\Block\Sidebar\Rss
 */
?>
<div class="widget block block-rss" data-bind="scope: 'blog-rss'">
    <div class="block-title">
        <img class="rss-icon" src="<?php echo $block->getViewFileUrl('Magetop_Blog::images/rss-icon.png') ?>">
        <strong><a target="_blan" href="<?php echo $this->getUrl('blog/rss/feed') ?>"><?php echo __('RSS Feed') ?></a></strong>
    </div>
</div>