<ul><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Home") ?>" target="_self" href="#"><span class="title"><?php echo __("Home") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Home") ?></h2><a class="mp-back" href="#">back</a><ul><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-phone" title="<?php echo __("Phones") ?>" target="_self" href="#"><span class="title"><?php echo __("Phones") ?></span></a><div class="mp-level"><h2 class="fa fa-phone"><?php echo __("Phones") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
<div class="grid-five-col">
<div>
<h5>Apple</h5>
<ul class="category-list">
<li><a href="#">iPhone 6 Plus</a>
</li>
<li><a href="#">iPhone 6</a>
</li>
<li><a href="#">iPhone 5s</a>
</li>
<li><a href="#">iPhone 5c</a>
</li>
<li><a href="#">iPhone 5</a>
</li>
<li><a href="#">iPhone 4s</a>
</li>
<li><a href="#">iPhone 4</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>Samsung</h5>
<ul class="category-list">
<li><a href="#">Z1</a>
</li>
<li><a href="#">Galaxy Grand</a>
</li>
<li><a href="#">Galaxy Core P</a>
</li>
<li><a href="#">Galaxy A5 Duos</a>
</li>
<li><a href="#">Galaxy A5</a>
</li>
<li><a href="#">Galaxy A3 Duos</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>Sony</h5>
<ul class="category-list">
<li><a href="#">Xperia E3</a>
</li>
<li><a href="#">Xperia Z3</a>
</li>
<li><a href="#">Xperia M2</a>
</li>
<li><a href="#">Xperia C3</a>
</li>
<li><a href="#">Xperia E1</a>
</li>
<li><a href="#">Xperia SP</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>LG</h5>
<ul class="category-list">
<li><a href="#">G Flex2</a>
</li>
<li><a href="#">L Prime</a>
</li>
<li><a href="#">G2 Lite</a>
</li>
<li><a href="#">G3 Dual-LTE</a>
</li>
<li><a href="#">F60</a>
</li>
<li><a href="#">L60</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>HTC</h5>
<ul class="category-list">
<li><a href="#">Desire 526G+</a>
</li>
<li><a href="#">Desire 826</a>
</li>
<li><a href="#">Desire 320</a>
</li>
<li><a href="#">Desire 620G</a>
</li>
<li><a href="#">One (M8 Eye)</a>
</li>
<li><a href="#">Desire 820</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>


</div>

<hr />
<div class="grid-five-col">
<div>
<h5>Motorola</h5>
<ul class="category-list">
<li><a href="#">Moto G 4G</a>
</li>
<li><a href="#">Moto Maxx</a>
</li>
<li><a href="#">Moto X</a>
</li>
<li><a href="#">Moto G 4G</a>
</li>
<li><a href="#">Luge</a>
</li>
<li><a href="#">RAZR i XT890</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>Huawei</h5>
<ul class="category-list">
<li><a href="#">Ascend Y520</a>
</li>
<li><a href="#">Honor 6 Plus</a>
</li>
<li><a href="#">Honor 4X</a>
</li>
<li><a href="#">Ascend Mate7</a>
</li>
<li><a href="#">Honor 3X Pro</a>
</li>
<li><a href="#">Y300II</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>Lenovo</h5>
<ul class="category-list">
<li><a href="#">A6000</a>
</li>
<li><a href="#">P90</a>
</li>
<li><a href="#">Vibe X2 Pro</a>
</li>
<li><a href="#">A916</a>
</li>
<li><a href="#">A319</a>
</li>
<li><a href="#">S90 Sisley</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>Xiaomi</h5>
<ul class="category-list">
<li><a href="#">Redmi 2</a>
</li>
<li><a href="#">Mi 4 LTE</a>
</li>
<li><a href="#">Redmi Note</a>
</li>
<li><a href="#">Mi 3</a>
</li>
<li><a href="#">Mi 2A</a>
</li>
<li><a href="#">Mi 2S</a>
</li>
<li><a href="#">Mi 2</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>

<div>
<h5>Asus</h5>
<ul class="category-list">
<li><a href="#">Zenfone C</a>
</li>
<li><a href="#">Fonepad 7</a>
</li>
<li><a href="#">Zenfone Zoom</a>
</li>
<li><a href="#">Zenfone 2</a>
</li>
<li><a href="#">Memo Pad 7</a>
</li>
<li><a href="#">Fone Pad 8</a>
</li>
<li><a class="read-more" href="#">View All</a>
</li>
</ul>


</div>


</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-tablet" title="<?php echo __("Tablets") ?>" target="_self" href="#"><span class="title"><?php echo __("Tablets") ?></span></a><div class="mp-level"><h2 class="fa fa-tablet"><?php echo __("Tablets") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
<div class="mb-row">
<div class="grid-column4">
<h5>Top Rated</h5>
<ul class="category-list">
<li><a href="#">iPad Air 2</a>
</li>
<li><a href="#">Asus Memo Pad 8</a>
</li>
<li><a href="#">Toshiba WT310</a>
</li>
<li><a href="#">Nexus 9</a>
</li>
<li><a href="#">Galaxy Tab 4 10.1</a>
</li>
<li><a href="#">Sony Xperia Z3</a>
</li>
<li><a href="#">Surface Pro 3</a>
</li>
</ul>


</div>

<div class="grid-column4">
<h5>Popular</h5>
<ul class="category-list">
<li><a href="#">Samsung Galaxy Tab 4 10.1</a>
</li>
<li><a href="#">iPad Air 2</a>
</li>
<li><a href="#">Samsung Galaxy Tab S 10.5</a>
</li>
<li><a href="#">Samsung Galaxy Tab 4 7.0</a>
</li>
<li><a href="#">Asus MeMO Pad 8</a>
</li>
<li><a href="#">Lenovo Yoga Tablet</a>
</li>
<li><a href="#">Toshiba Encore 2</a>
</li>
</ul>


</div>

<div class="grid-column4">
<h5>Best Value</h5>
<ul class="category-list">
<li><a href="#">iPad Air 2</a>
</li>
<li><a href="#">Samsung Galaxy Tab S</a>
</li>
<li><a href="#">Sony Xperia Z3</a>
</li>
<li><a href="#">Sony Xperia Z2</a>
</li>
<li><a href="#">Nexus 9</a>
</li>
<li><a href="#">iPad Mini 3</a>
</li>
<li><a href="#">iPad Mini 2</a>
</li>
</ul>


</div>


</div>

<div class="row-0 space-2"><a class="btn-lg w-100 bg-design" href="#"><i class="fa fa-question-circle fa-fw"></i> Not sure which tablet is right for you? View all tablets here.</a>
</div>

<div class="mb-row">
<div class="grid-column6">
<h5>Featured Tablet</h5>
<div class="container-oh overlay-icon w-30"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/tablet.jpg" />
<div class="list-socail">
</div>


</div>

<h6>iPad Air 2</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, accusantium, nemo, quibusdam numquam et veritatis recusandae illo provident nesciunt vel inventore suscipit beatae quae perferendis natus aliquam quibusdam numquam et...</p>
<em> <a class="btn btn-small" href="#">Read more<i class="fa fa-caret-right"></i></a> </em>
</div>

<div class="grid-column6">
<h5>Spotlight Review</h5>
<div class="container-oh overlay-icon w-30"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/tablet.jpg" />
<div class="list-socail">
</div>


</div>

<h6>Samsung Galaxy Tab 4 10.1</h6>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, accusantium, nemo, quibusdam numquam et veritatis recusandae illo provident nesciunt vel inventore suscipit beatae quae perferendis natus aliquam quibusdam numquam et...</p>
<em> <a class="btn btn-small" href="#">Read more<i class="fa fa-caret-right"></i></a> </em>
</div>


</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-windows" title="<?php echo __("Desktops") ?>" target="_self" href="#"><span class="title"><?php echo __("Desktops") ?></span></a><div class="mp-level"><h2 class="fa fa-windows"><?php echo __("Desktops") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="lg-row">
		<div  class="grid-column6">
			<h5>Best Seller</h5>
			<div class="sub-row">
				<div class="grid-column4">
					<div class="container-ov overlay-icon">
						<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/desktop.jpg">
						<a href="#" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="#" class="fa fa-google-plus"></a>
						<a href="#" class="fa fa-pinterest"></a>
					
</div>

				
</div>

				<div class="grid-column8">
					<h6>Dell Inspiron Desktop</h6>
					<ul class="l-specs">
						<li><i class="fa fa-check fa-fw"></i>Windows 8.1 64-bit
</li>
						<li><i class="fa fa-check fa-fw"></i>Technical details: Core i7 Processor; 4GB memory; 1TB hard drive
</li>
						<li><i class="fa fa-check fa-fw"></i>Special features: Built-in wireless networking and bluetooth
</li>
					</ul>

					<em>
						<a href="#" class="btn btn-small">Detailed Specs<i class="fa fa-caret-right"></i></a>
					</em>
				
</div>

			
</div>

			<h5>Best Buy</h5>
			<div class="sub-row">
				<div class="grid-column4">
					<div class="container-ov overlay-icon">
						<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/desktop.jpg">
						<a href="#" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="#" class="fa fa-google-plus"></a>
						<a href="#" class="fa fa-pinterest"></a>
					
</div>

				
</div>

				<div class="grid-column8">
					<h6>HP - Pavilion Slimline Desktop</h6>
					<ul class="l-specs">
						<li><i class="fa fa-check fa-fw"></i>Windows 8.1 64-bit
</li>
						<li><i class="fa fa-check fa-fw"></i>Technical details: AMD E-Series processor; 4GB memory; 500GB hard drive
</li>
						<li><i class="fa fa-check fa-fw"></i>Special features: Built-in wireless networking and bluetooth
</li>
					</ul>

					<em>
						<a href="#" class="btn btn-small">Detailed Specs<i class="fa fa-caret-right"></i></a>
					</em>
				
</div>

			
</div>

			<h5 class="theme-margin-top">Worth Considering</h5>
			<div class="sub-row">
				<div class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Apple Mac Pro</a>
</li>
						<li><a href="#">Dell XPS 27</a>
</li>
					</ul>

				
</div>

				<div class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Apple 21.5" iMac</a>
</li>
						<li><a href="#">Lenovo IdeaCentre</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column6">
			<div class="sub-row">
				<div  class="grid-column6">
					<h5>Current Offers</h5>
					<ul class="category-list">
						<li><a href="#">Free Shipping</a>
</li>
						<li><a href="#">Special Offers</a>
</li>
						<li><a href="#">On Sale</a>
</li>
						<li><a href="#">Outlet Items</a>
</li>
						<li><a href="#">Package Deals</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Brands</h5>
					<ul class="category-list">
						<li><a href="#">HP</a>
</li>
						<li><a href="#">Asus</a>
</li>
						<li><a href="#">Lenovo</a>
</li>
						<li><a href="#">Dell</a>
</li>
						<li><a href="#">Apple</a>
</li>
						<li><a href="#">Acer</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Collection</h5>
					<ul class="category-list">
						<li><a href="#">Gaming Series</a>
</li>
						<li><a href="#">Only at Best Buy</a>
</li>
						<li><a href="#">Premium Collection</a>
</li>
						<li><a href="#">Business Series</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Processor</h5>
					<ul class="category-list">
						<li><a href="#">Intel</a>
</li>
						<li><a href="#">AMD</a>
</li>
						<li><a href="#">IntelÂ®</a>
</li>
						<li><a href="#">AllWinner</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Features</h5>
					<ul class="category-list">
						<li><a href="#">Touch Screen</a>
</li>
						<li><a href="#">Portable Design</a>
</li>
						<li><a href="#">ENERGY Certified</a>
</li>
						<li><a href="#">EPEAT Qualified</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Operating System</h5>
					<ul class="category-list">
						<li><a href="#">Windows 7</a>
</li>
						<li><a href="#">Windows 8</a>
</li>
						<li><a href="#">Mac OS</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-laptop" title="<?php echo __("Laptops") ?>" target="_self" href="#"><span class="title"><?php echo __("Laptops") ?></span></a><div class="mp-level"><h2 class="fa fa-laptop"><?php echo __("Laptops") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<h5>People's Choice</h5>
	<div class="mb-row space-3">
		<div  class="grid-column3">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption a-center item-flex">
					<h3>$1745.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6 class="a-center">Apple MacBook Pro</h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, nam, ex quasi provid explicabo consentus... 
				<em class="l-block">
					<a href="#" class="btn w-100">Read more<i class="fa fa-caret-right"></i></a>
				</em>
			</p>
		
</div>

		<div  class="grid-column3">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption a-center item-flex">
					<h3>$995.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6 class="a-center">Apple MacBook Air</h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, nam, ex quasi provid explicabo consentus... 
				<em class="l-block">
					<a href="#" class="btn w-100">Read more<i class="fa fa-caret-right"></i></a>
				</em>
			</p>
		
</div>

		<div  class="grid-column3">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption a-center item-flex">
					<h3>$915.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6 class="a-center">Microsoft Surface Pro 3</h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, nam, ex quasi provid explicabo consentus... 
				<em class="l-block">
					<a href="#" class="btn w-100">Read more<i class="fa fa-caret-right"></i></a>
				</em>
			</p>
		
</div>

		<div  class="grid-column3">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption a-center item-flex">
					<h3>$895.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6 class="a-center">Toshiba Chromebook 2</h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, nam, ex quasi provid explicabo consentus... 
				<em class="l-block">
					<a href="#" class="btn w-100">Read more<i class="fa fa-caret-right"></i></a>
				</em>
			</p>
		
</div>

	
</div>

	<div class="mb-row">
		<div  class="grid-column3">
			<h5>Price</h5>
			<ul class="category-list">
				<li><a href="#">Less than $229</a>
</li>
				<li><a href="#">$244 - $517</a>
</li>
				<li><a href="#">$517 - $698</a>
</li>
				<li><a href="#">$699 - $868</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL PRICES<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

		<div  class="grid-column3">
			<h5>Manufacturer</h5>
			<ul class="category-list">
				<li><a href="#">Dell, Inc.</a>
</li>
				<li><a href="#">Apple</a>
</li>
				<li><a href="#">Samsung</a>
</li>
				<li><a href="#">Toshiba</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW MANUFACTURERS<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

		<div  class="grid-column3">
			<h5>Screen Size</h5>
			<ul class="category-list">
				<li><a href="#">17" and larger</a>
</li>
				<li><a href="#">16" and less</a>
</li>
				<li><a href="#">15" and less</a>
</li>
				<li><a href="#">14" and less</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL SCREEN SIZES<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

		<div  class="grid-column3">
			<h5>Weight</h5>
			<ul class="category-list">
				<li><a href="#">1 lb or less</a>
</li>
				<li><a href="#">2 lbs or less</a>
</li>
				<li><a href="#">3 lbs or less</a>
</li>
				<li><a href="#">4 lbs or less</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL WEIGHTS<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-book" title="<?php echo __("Netbooks") ?>" target="_self" href="#"><span class="title"><?php echo __("Netbooks") ?></span></a><div class="mp-level"><h2 class="fa fa-book"><?php echo __("Netbooks") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<h5>Netbooks</h5>
	<div class="mb-row space-t2">
		<div  class="grid-column3 a-center">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption item-flex">
					<h3>$395.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6>Acer Aspire C720-3605 Chromebook</h6>
			<em>
				<a href="#" class="read-more small-font">VIEW DETAILS<i class="fa fa-caret-right fa-fw"></i></a>
			</em>
		
</div>

		<div  class="grid-column3 a-center">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">	
				<div class="flipY-caption item-flex">
					<h3>$375.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6>ASUS C300MA-DH02 Chromebook</h6>
			<em>
				<a href="#" class="read-more small-font">VIEW DETAILS<i class="fa fa-caret-right fa-fw"></i></a>
			</em>
		
</div>

		<div  class="grid-column3 a-center">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption item-flex">
					<h3>$365.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6>Lenovo G50-80 (80E501U3US) X11-50</h6>
			<em>
				<a href="#" class="read-more small-font">VIEW DETAILS<i class="fa fa-caret-right fa-fw"></i></a>
			</em>
		
</div>

		<div  class="grid-column3 a-center">
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/notebook.jpg" class="full-w">
				<div class="flipY-caption item-flex">
					<h3>$385.00</h3>
					<ul class="inline-list">
						<li><a href="#"><i class="fa fa-link"></i></a>
</li>
						<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
						<li><a href="#"><i class="fa fa-star"></i></a>
</li>
						<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
					</ul>

				
</div>

			
</div>

			<h6>Acer Aspire V3-572P-78MT 15.6"</h6>
			<em>
				<a href="#" class="read-more small-font">VIEW DETAILS<i class="fa fa-caret-right fa-fw"></i></a>
			</em>
		
</div>

	
</div>

	<div class="mb-row space-3t">
		<div  class="grid-column3">
			<h5>Platform</h5>
			<ul class="category-list">
				<li><a href="#">Windows 7</a>
</li>
				<li><a href="#">Windows 8</a>
</li>
				<li><a href="#">Windows 10</a>
</li>
				<li><a href="#">Linux</a>
</li>
				<li><a href="#">Mac OS</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL PLATFORMS<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

		<div  class="grid-column3">
			<h5>Manufacturer</h5>
			<ul class="category-list">
				<li><a href="#">Hewlett - Packard</a>
</li>
				<li><a href="#">AsusTek Computers</a>
</li>
				<li><a href="#">Lenovo</a>
</li>
				<li><a href="#">Samsung</a>
</li>
				<li><a href="#">Dell, Inc.</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL MANUFACTURERS<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

		<div  class="grid-column3">
			<h5>Screen Size</h5>
			<ul class="category-list">
				<li><a href="#">10 to 13 inches</a>
</li>
				<li><a href="#">7 to 10 inches</a>
</li>
				<li><a href="#">5 to 7 inches</a>
</li>
				<li><a href="#">15 to 17 inches</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL SCREEN SIZES<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

		<div  class="grid-column3">
			<h5>Weight</h5>
			<ul class="category-list">
				<li><a href="#">Less than 4 lbs</a>
</li>
				<li><a href="#">Less than 5 lbs</a>
</li>
				<li><a href="#">Less than 6 lbs</a>
</li>
				<li><a href="#">Less than 3 lbs</a>
</li>
				<li><a href="#">Less than 2 lbs</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">VIEW ALL WEIGHTS<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-desktop" title="<?php echo __("Monitors") ?>" target="_self" href="#"><span class="title"><?php echo __("Monitors") ?></span></a><div class="mp-level"><h2 class="fa fa-desktop"><?php echo __("Monitors") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<h5>Monitors Product Line</h5>
	<div class="grid-five-col">
		<div>
			<h6 class="a-center">Touch Displays</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">10 Point Touch</a>
</li>
						<li><a href="#">Capacitive Touch</a>
</li>
						<li><a href="#">Dual Point Touch</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Professional</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Ultra HD</a>
</li>
						<li><a href="#">Wide AMVA LED</a>
</li>
						<li><a href="#">Multiple Sources</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Graphics</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Clear panels</a>
</li>
						<li><a href="#">2W speakers</a>
</li>
						<li><a href="#">Superior rendering</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Entertainment</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">PLS panels</a>
</li>
						<li><a href="#">Flicker free</a>
</li>
						<li><a href="#">Color accuracy</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Value</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Low energy</a>
</li>
						<li><a href="#">Viewing comfort</a>
</li>
						<li><a href="#">Slim bezel design</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

	
</div>

	<div class="grid-five-col space-t3">
		<div>
			<h6 class="a-center">Smart Displays</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">GMS certified</a>
</li>
						<li><a href="#">Screen mirroring</a>
</li>
						<li><a href="#">Internet capable</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">IPS Monitors</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Brilliant colors</a>
</li>
						<li><a href="#">Frameless display</a>
</li>
						<li><a href="#">Superclear image</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Gaming Monitors</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Blazing speed</a>
</li>
						<li><a href="#">Better visibility</a>
</li>
						<li><a href="#">Unparallel clarity</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Privacy Screens</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Anti - glare</a>
</li>
						<li><a href="#">Anti - reflective</a>
</li>
						<li><a href="#">Durable designs</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

		<div>
			<h6 class="a-center">Curve Display</h6>
			<div class="container-img">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/screen.jpg">
				<div class="slideDown-caption a-center">
					<ul class="small-list">
						<li><a href="#">Curved Screen</a>
</li>
						<li><a href="#">Sleek designs</a>
</li>
						<li><a href="#">Realistic images</a>
</li>
						<li class="margin-top-half"><a href="#">View All</a>
</li>
					</ul>

				
</div>

			
</div>

			<p class="small-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, aliquid fuga obcaecati.</p>
		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-video-camera" title="<?php echo __("Projectors") ?>" target="_self" href="#"><span class="title"><?php echo __("Projectors") ?></span></a><div class="mp-level"><h2 class="fa fa-video-camera"><?php echo __("Projectors") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="lg-row">
		<div  class="grid-column6">
			<div class="sub-row">
				<div  class="grid-column6">
					<h5>Native Resolution</h5>
					<ul class="category-list">
						<li><a href="#">800 x 600</a>
</li>
						<li><a href="#">1024 x 768</a>
</li>
						<li><a href="#">1280 x 800</a>
</li>
						<li><a href="#">1366 x 768</a>
</li>
						<li><a href="#">1440 x 1050</a>
</li>
						<li><a href="#">1920 x 1080</a>
</li>
						<li><a href="#">2560 x 1080</a>
</li>
						<li><a href="#">2560 x 1600</a>
</li>
						<li><a href="#">4K</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Brightness</h5>
					<ul class="category-list">
						<li><a href="#">Under 2000</a>
</li>
						<li><a href="#">2100 - 3000</a>
</li>
						<li><a href="#">3000 - 4000</a>
</li>
						<li><a href="#">4000 - 5000</a>
</li>
						<li><a href="#">5000 - 6000</a>
</li>
						<li><a href="#">6000 - 7000</a>
</li>
						<li><a href="#">7000 Up</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Brands</h5>
					<ul class="category-list">
						<li><a href="#">Acer</a>
</li>
						<li><a href="#">BenQ</a>
</li>
						<li><a href="#">Canon</a>
</li>
						<li><a href="#">Epson</a>
</li>
						<li><a href="#">InFocus</a>
</li>
						<li><a href="#">NEC</a>
</li>
						<li><a href="#">Panasonic</a>
</li>
						<li><a href="#">Sony</a>
</li>
						<li><a href="#">ViewSonic</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Projector Type</h5>
					<ul class="category-list">
						<li><a href="#">Portable</a>
</li>
						<li><a href="#">Desktop</a>
</li>
						<li><a href="#">Installation</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column6">
			<div class="full-r">
				<h5>Editor's Pick</h5>
				<div class="container-ov overlay-icon w-40">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/projector.jpg">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-twitter"></a>
					<a href="#" class="fa fa-google-plus"></a>
					<a href="#" class="fa fa-pinterest"></a>
				
</div>

				<h6>Sony VPL-VW1000ES 4K 3D</h6>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil, asperiores accusantium facilis... 																												
					<em>
						<a href="#" class="read-more-paragraph">Read more<i class="fa fa-caret-right"></i></a>
					</em>
				</p>
			
</div>

			<div class="full-r">
				<h5>Top Picks</h5>
				<div class="container-ov overlay-icon w-40">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/projector.jpg">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-twitter"></a>
					<a href="#" class="fa fa-google-plus"></a>
					<a href="#" class="fa fa-pinterest"></a>
				
</div>

				<h6>Epson 5030UBe 3D LCD</h6>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus quos quis excepturi placeat inventore possimus nihil sed similique! Alias, quos. Perferendis optio assumenda iusto ratione at, voluptas... 
					<em>
						<a href="#" class="read-more-paragraph">Read more<i class="fa fa-caret-right"></i></a>
					</em>
				</p>
			
</div>
	
			<div class="full-r">
				<div class="container-ov overlay-icon w-40">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/projector.jpg">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-twitter"></a>
					<a href="#" class="fa fa-google-plus"></a>
					<a href="#" class="fa fa-pinterest"></a>
				
</div>

				<h6>BenQ W7000 3D DLP</h6>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt consectetur rerum modi, expedita enim odit incidunt, mollitia, dolorem animi accusantium perspiciatis, neque ipsa ex tenetur... 
					<em>
						<a href="#" class="read-more-paragraph">Read more<i class="fa fa-caret-right"></i></a>
					</em>
				</p>
			
</div>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-camera" title="<?php echo __("Cameras") ?>" target="_self" href="#"><span class="title"><?php echo __("Cameras") ?></span></a><div class="mp-level"><h2 class="fa fa-camera"><?php echo __("Cameras") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="lg-row">
		<div  class="grid-column6">
			<h5>Camera Brands</h5>
			<div class="sub-row">
				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Canon</a>
</li>
						<li><a href="#">Fujifilm</a>
</li>
						<li><a href="#">Leica</a>
</li>
						<li><a href="#">Nikon</a>
</li>
						<li><a href="#">Olympus</a>
</li>
						<li><a href="#">Panason
</li>ic</a>
					</ul>

				
</div>

				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Pentax</a>
</li>
						<li><a href="#">Ricoh</a>
</li>
						<li><a href="#">Samsung</a>
</li>
						<li><a href="#">Sigma</a>
</li>
						<li><a href="#">Sony</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column6">
			<h5>Now Shooting</h5>
			<div class="sub-row">
				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Nikon D810</a>
</li>
						<li><a href="#">Sony A77 II</a>
</li>
						<li><a href="#">Fujifilm X100T</a>
</li>
						<li><a href="#">Canon 7D Mark II</a>
</li>
						<li><a href="#">Fujifilm X100T</a>
</li>
						<li><a href="#">Samsung NX3000</a>
</li>
						<li><a href="#">Olympus E-M5</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Fujifilm X30</a>
</li>
						<li><a href="#">Canon G7X</a>
</li>
						<li><a href="#">Panasonic LX100</a>
</li>
						<li><a href="#">Panasonic GM5</a>
</li>
						<li><a href="#">Sony A7 Mark II</
</li>a>
						<li><a href="#">Canon 70D</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column6">
			<h5>Featured Camera Review</h5>
			<div class="container-ov overlay-icon w-40">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/camera.jpg">
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-google-plus"></a>
				<a href="#" class="fa fa-pinterest"></a>
			
</div>

			<h6>Canon 5D Mark III</h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, accusantium, nemo, quibusdam numquam et veritatis recusandae illo provident nesciunt vel inventore suscipit beatae quae perferendis natus aliquam nam voluptas quas!</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, accusantium, nemo, quibusdam numquam et veritatis quae quas... 																															
				<em class="d-block space-t2">
					<a href="#" class="btn">Read more<i class="fa fa-caret-right"></i></a>
				</em>
			</p>
		
</div>

		<div  class="grid-column6">
			<h5>Top Camera - Head to Head Battle</h5>
			<ul class="category-list">
				<li><a href="#">Canon 6D vs Nikon D610</a>
</li>
				<li><a href="#">Sony RX10 vs Panasonic FZ1000</a>
</li>
				<li><a href="#">Sony RX1000 II vs Sony RX100 III</a>
</li>
				<li><a href="#">Sony RX100 vs Sony RX100 II</a>
</li>
				<li><a href="#">Sony RX100 vs Sony RX1000 III</a>
</li>
				<li><a href="#">Canon 70D vs Nikon D7100</a>
</li>
				<li><a href="#">Canon 6D vs Canon 5D Mark III</a>
</li>
				<li><a href="#">Canon T5i vs Canon T4i</a>
</li>
				<li><a href="#">Olympus E-M1 vs Olympus E-M5</a>
</li>
				<li><a href="#">Sony RX100 vs Sony RX100 Mark II</a>
</li>
			</ul>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-gamepad" title="<?php echo __("Consoles") ?>" target="_self" href="#"><span class="title"><?php echo __("Consoles") ?></span></a><div class="mp-level"><h2 class="fa fa-gamepad"><?php echo __("Consoles") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="lg-row">
		<div  class="grid-column6">
			<div class="full-r">
				<h5>Console of the Year</h5>
				<div class="container-ov overlay-icon w-40">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/console.jpg">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-twitter"></a>
					<a href="#" class="fa fa-google-plus"></a>
					<a href="#" class="fa fa-pinterest"></a>
				
</div>

				<h6>Sony PlayStation 4</h6>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil, asperiores accusantium ea quis esse facilis itaque assumenda... 																																
					<em>
						<a href="#" class="read-more-paragraph">Read more<i class="fa fa-caret-right"></i></a>
					</em>
				</p>
			
</div>

			<div class="full-r">
				<h5>Featured Home Console</h5>
				<div class="container-ov overlay-icon w-40">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/console.jpg">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-twitter"></a>
					<a href="#" class="fa fa-google-plus"></a>
					<a href="#" class="fa fa-pinterest"></a>
				
</div>

				<h6>Microsoft Xbox 360</h6>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam expedita molestias, blanditiis laboriosam incidunt accusantium omnis placeat voluptas architecto numquam mollitia, aliquam cumque. Nulla, error aut tempore asperiores, autem alias. Consectetur adipisicing elit. Magnam expedita molestias, blanditiis laboriosam incidunt accusantium omnis placeat.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil, asperiores accusantium ea quis esse facilis itaque assumenda. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate, quod, dicta.
					<em>
						<a href="#" class="read-more-paragraph">Read more<i class="fa fa-caret-right"></i></a>
					</em>
				</p>	
			
</div>

		
</div>

		<div  class="grid-column6">
			<div class="sub-row">
				<div  class="grid-column6">
					<h5>Game Format</h5>
					<ul class="category-list">
						<li><a href="#">Cartridge</a>
</li>
						<li><a href="#">Optical Disc</a>
</li>
						<li><a href="#">Downloadables</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>WIFI</h5>
					<ul class="category-list">
						<li><a href="#">Yes</a>
</li>
						<li><a href="#">No</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Companies</h5>
					<ul class="category-list">
						<li><a href="#">Nintendo</a>
</li>
						<li><a href="#">Sony</a>
</li>
						<li><a href="#">NVIDIA</a>
</li>
						<li><a href="#">Tiger Electronics</a>
</li>
						<li><a href="#">Atari</a>
</li>
						<li><a href="#">Steamboy Machine</a>
</li>
						<li><a href="#">JXD</a>
</li>
						<li><a href="#">Dingo</a>
</li>
						<li><a href="#">GamePark</a>
</li>
						<li><a href="#">Tiger Telematics</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Recent Release</h5>
					<ul class="category-list">
						<li><a href="#">Microsoft Xbox 360</a>
</li>
						<li><a href="#">PlayStation 3 Slim</a>
</li>
						<li><a href="#">PlayStation 4</a>
</li>
						<li><a href="#">Xbox One</a>
</li>
						<li><a href="#">PlayStation Vita</a>
</li>
						<li><a href="#">New 3DS</a>
</li>
						<li><a href="#">NVIDIA Shield</a>
</li>
						<li><a href="#">DS Lite</a>
</li>
						<li><a href="#">Dingo A320</a>
</li>
						<li><a href="#">2DS</a>
</li>
						<li><a href="#">GP2X WIZ</a>
</li>
						<li><a href="#">Pandora</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-database" title="<?php echo __("Hardware") ?>" target="_self" href="#"><span class="title"><?php echo __("Hardware") ?></span></a><div class="mp-level"><h2 class="fa fa-database"><?php echo __("Hardware") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
<div class="mb-row">
<div class="grid-column4">
<h5>Processors</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/processor.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> Desktop CPUs</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Server CPUs</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Mobile CPUs</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>

<div class="grid-column4">
<h5>Motherboards</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/motherboard.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> For Intel</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> For AMD</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> For MIni PCs</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>

<div class="grid-column4">
<h5>Graphics Devices</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/videocard.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> Desktop</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Professional</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Workstation</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>


</div>

<div class="mb-row">
<div class="grid-column4">
<h5>Computer Cases</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/casing.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> Full ATX</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Mini-ATX</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Gaming</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>

<div class="grid-column4">
<h5>Power Supplies</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/psu.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> 80+ Bronze</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> 80+ Gold</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> 80+ Platinum</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>

<div class="grid-column4">
<h5>Memory</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/ram.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> Desktop</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Portable</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Flash Memory</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>


</div>

<div class="mb-row">
<div class="grid-column4">
<h5>Storage</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/storage.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> Hard Drive</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> External Drive</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Net Storage</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>

<div class="grid-column4">
<h5>Optical Drives</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/optical.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> BR Burners</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> DVD Burners</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> External Drives</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>

<div class="grid-column4">
<h5>Cooling</h5>
<div class="space-t2">
<div class="sub-row">
<div class="grid-column6">
<div class="container-img"><img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/cooling.jpg" />
<div class="slideDown-caption a-center h-100">
<ul class="small-list">
<li><a href="#">Top 10</a>
</li>
<li><a href="#">Popular</a>
</li>
<li><a href="#">Value</a>
</li>
</ul>


</div>


</div>


</div>

<div class="grid-column6">
<ul class="l-specs">
<li><a href="#"><i class="fa fa-caret-right"></i> Air Coolers</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Liquid Coolers</a>
</li>
<li><a href="#"><i class="fa fa-caret-right"></i> Case Fans</a>
</li>
<li><a class="read-more" href="#"><i class="fa fa-caret-right"></i> Show All</a>
</li>
</ul>


</div>


</div>


</div>


</div>


</div>

<div class="mb-row">
<div class="grid-column12 a-center"><a class="btn-lg bg-design space-2 w-100" href="#"><i class="fa fa-question-circle"></i> Is your PC broken or need some upgrade? View all hardware products here.</a>
</div>


</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-shield" title="<?php echo __("Software") ?>" target="_self" href="#"><span class="title"><?php echo __("Software") ?></span></a><div class="mp-level"><h2 class="fa fa-shield"><?php echo __("Software") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="mb-row">
		<div  class="grid-column3">
			<h5>Productivity</h5>
			<div class="space-t2">
				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$219.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Microsoft Office 2015 Edition</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$19.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Corel PDF Fusion Pro</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$48.21
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Nuance Dragon Speaking 13</a>
					
</div>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column3">
			<h5>Utility</h5>
			<div class="space-t2">
				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$28.98
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Acronis True Image 2015</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$37.75
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">ESET NOD32 Antivirus 2015</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$40.22
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Kaspersky Internet Security 2015</a>
					
</div>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column3">
			<h5>Multimedia</h5>
			<div class="space-t2">
				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$219.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Nero 2015</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$50.97
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Corel PaintShop Pro X7 Ultimate</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$219.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Adobe PhotoShop Elements 13</a>
					
</div>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column3">
			<h5>Operating Systems</h5>
			<div class="space-t2">
				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$989.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Windows 7 Ultimate</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$915.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Windows 7 Professional</a>
					
</div>

				
</div>

				<div class="sub-row space-3">
					<div  class="grid-column6">
						<div class="container-img a-center">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/software.jpg">
							<div class="slideDown-caption">
								<ul class="small-list item-flex">
									<li class="lg-font">$915.00
</li>
									<li class="space-t1">
										<a href="#"><i class="fa fa-link"></i></a>
										<a href="#"><i class="fa fa-comment"></i></a>
										<br>
										<a href="#"><i class="fa fa-star"></i></a>
										<a href="#"><i class="fa fa-shopping-cart"></i></a>
									
</li>
								</ul>

							
</div>

						
</div>

					
</div>

					<div  class="grid-column6">
						<a href="#">Server 2016</a>
					
</div>

				
</div>

			
</div>

		
</div>

	
</div>

	<div class="a-center">
		<a href="#" class="btn-lg bg-design space-2 w-100"><i class="fa fa-question-circle fa-fw"></i> Not sure which software do you need? View all software products here.</a>
	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-keyboard-o" title="<?php echo __("Peripherals") ?>" target="_self" href="#"><span class="title"><?php echo __("Peripherals") ?></span></a><div class="mp-level"><h2 class="fa fa-keyboard-o"><?php echo __("Peripherals") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="mb-row">
		<div  class="grid-column4">
			<h5>External Hard Drives</h5>
			<ul class="category-list">
				<li><a href="#">1 TB & Up</a>
</li>
				<li><a href="#">500 GB to 999 GB</a>
</li>
				<li><a href="#">500 GB and Under</a>
</li>
				<li><a href="#" class="read-more">View All</a>
</li>
			</ul>

			<h5>Computer Keyboards</h5>
			<ul class="category-list">
				<li><a href="#">Wireless</a>
</li>
				<li><a href="#">USB</a>
</li>
				<li><a href="#">Gaming</a>
</li>
				<li><a href="#" class="read-more">View All</a>
</li>
			</ul>

			<h5>Computer Mice</h5>
			<ul class="category-list">
				<li><a href="#">Wireless</a>
</li>
				<li><a href="#">USB</a>
</li>
				<li><a href="#">Gaming</a>
</li>
				<li><a href="#" class="read-more">View All</a>
</li>
			</ul>

			<h5>PC Headsets</h5>
			<ul class="category-list">
				<li><a href="#">Gaming</a>
</li>
				<li><a href="#">Wireless</a>
</li>
				<li><a href="#">Wired</a>
</li>
				<li><a href="#" class="read-more">View All</a>
</li>
			</ul>

		
</div>

		<div  class="grid-column8">
			<h5>Top Rated Peripherals</h5>
			<div class="item-flex">
				<div class="sub-row space-t2">
					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/keyboard.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$141.78</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Thunder K7</h6>
						
</div>

					
</div>

					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/mouse1.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$79.99</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Corsair M95 Mouse</h6>
						
</div>

					
</div>

					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/mouse2.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$90.00</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Mionix Naos 7000</h6>
						
</div>

					
</div>

				
</div>

				<div class="sub-row space-t2">
					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/gamepad.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$15.99</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Logitech Game Pad</h6>
						
</div>

					
</div>

					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/ehdd.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$54.00</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>WD My Passport</h6>
						
</div>

					
</div>

					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/flashdrive1.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$11.93</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Kingston XC</h6>
						
</div>

					
</div>

				
</div>

				<div class="sub-row space-t2">
					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/keyboard.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$155.99</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Rapoo 7</h6>
						
</div>

					
</div>

					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/mouse2.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$24.00</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Corsair X11T</h6>
						
</div>

					
</div>

					<div  class="grid-column4">
						<div class="a-center">
							<div class="container-img">
								<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/flashdrive2.jpg">
								<div class="flipY-caption a-center item-flex">
									<h3>$19.93</h3>
									<ul class="inline-list">
										<li><a href="#"><i class="fa fa-link"></i></a>
</li>
										<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
										<li><a href="#"><i class="fa fa-star"></i></a>
</li>
										<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
									</ul>

								
</div>

							
</div>

							<h6>Transcend XKT</h6>
						
</div>

					
</div>

				
</div>

			
</div>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-headphones" title="<?php echo __("Accessories") ?>" target="_self" href="#"><span class="title"><?php echo __("Accessories") ?></span></a><div class="mp-level"><h2 class="fa fa-headphones"><?php echo __("Accessories") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="lg-row">
		<div  class="grid-column8">
			<h5>Best Buy Items</h5>
			<div class="sub-row space-t2">
				<div  class="grid-column4">
					<div class="a-center">
						<div class="container-img">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/charger.jpg">
							<div class="flipY-caption a-center item-flex">
								<h3>$24.99</h3>
								<ul class="inline-list">
									<li><a href="#"><i class="fa fa-link"></i></a>
</li>
									<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
									<li><a href="#"><i class="fa fa-star"></i></a>
</li>
									<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
								</ul>

							
</div>
	
						
</div>

						<h6>Laptop Charger</h6>
					
</div>

				
</div>

				<div  class="grid-column4">
					<div class="a-center">
						<div class="container-img">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/mat.jpg">
							<div class="flipY-caption a-center item-flex">
								<h3>$17.50</h3>
								<ul class="inline-list">
									<li><a href="#"><i class="fa fa-link"></i></a>
</li>
									<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
									<li><a href="#"><i class="fa fa-star"></i></a>
</li>
									<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
								</ul>

							
</div>

						
</div>

						<h6>Dual Fan Mat</h6>
					
</div>

				
</div>

				<div  class="grid-column4">
					<div class="a-center">
						<div class="container-img">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/adapter.jpg">
							<div class="flipY-caption a-center item-flex">
								<h3>$8.45</h3>
								<ul class="inline-list">
									<li><a href="#"><i class="fa fa-link"></i></a>
</li>
									<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
									<li><a href="#"><i class="fa fa-star"></i></a>
</li>
									<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
								</ul>

							
</div>

						
</div>

						<h6>USB Adapter</h6>
					
</div>

				
</div>

			
</div>

			<div class="sub-row space-t2">
				<div  class="grid-column4">
					<div class="a-center">
						<div class="container-img">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/wipes.jpg">
							<div class="flipY-caption a-center item-flex">
								<h3>$2.17</h3>
								<ul class="inline-list">
									<li><a href="#"><i class="fa fa-link"></i></a>
</li>
									<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
									<li><a href="#"><i class="fa fa-star"></i></a>
</li>
									<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
								</ul>

							
</div>

						
</div>

						<h6>Monitor Wipes</h6>
					
</div>

				
</div>

				<div  class="grid-column4">
					<div class="a-center">
						<div class="container-img">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/protector.jpg">
							<div class="flipY-caption a-center item-flex">
								<h3>$15.75</h3>
								<ul class="inline-list">
									<li><a href="#"><i class="fa fa-link"></i></a>
</li>
									<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
									<li><a href="#"><i class="fa fa-star"></i></a>
</li>
									<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
								</ul>

							
</div>

						
</div>

						<h6>Screen Protector</h6>
					
</div>

				
</div>

				<div  class="grid-column4">
					<div class="a-center">
						<div class="container-img">
							<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/powerbank.jpg">
							<div class="flipY-caption a-center item-flex">
								<h3>$84.30</h3>
								<ul class="inline-list">
									<li><a href="#"><i class="fa fa-link"></i></a>
</li>
									<li><a href="#"><i class="fa fa-comment"></i></a>
</li>
									<li><a href="#"><i class="fa fa-star"></i></a>
</li>
									<li><a href="#"><i class="fa fa-shopping-cart"></i></a>
</li>
								</ul>

							
</div>

						
</div>

						<h6>Power Banks</h6>
					
</div>

				
</div>

			
</div>

			<div class="mb-row">
				<div  class="grid-column6">
					<h5>Cleaning Equipments</h5>
					<ul class="category-list">
						<li><a href="#">Air Dusters</a>
</li>
						<li><a href="#">Cleaning Cloths</a>
</li>
						<li><a href="#">Cleaning Kits</a>
</li>
						<li><a href="#">Cleaning Wipes</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<h5>Discs & Labels</h5>
					<ul class="category-list">
						<li><a href="#">Blu-ray Discs</a>
</li>
						<li><a href="#">CD-R/RW</a>
</li>
						<li><a href="#">DVD+R/RW</a>
</li>
						<li><a href="#">DVD-R/RW</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column4">
			<h5>Cables & Connectors</h5>
			<ul class="category-list">
				<li><a href="#">USB Cables & Hubs</a>
</li>
				<li><a href="#">FireWire Cables</a>
</li>
				<li><a href="#">KVM Cables</a>
</li>
				<li><a href="#">Network Cables</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">MORE CABLES <i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

			<h5>Laptop Accessories</h5>
			<ul class="category-list">
				<li><a href="#">Bags and Cases</a>
</li>
				<li><a href="#">Batteries</a>
</li>
				<li><a href="#">Cooling Pads</a>
</li>
				<li><a href="#">Security Locks</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">MORE LAPTOP ACCESSORIES <i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>
					
			<h5>Monitor Accessories</h5>
			<ul class="category-list">
				<li><a href="#">Privacy Screens</a>
</li>
				<li><a href="#">Screen Protectors</a>
</li>
				<li><a href="#">Monitor Mounts</a>
</li>
				<li><a href="#">Monitor Stands</a>
</li>
				<li class="no-bullet"><a href="#" class="small-font read-more">MORE MONITOR ACCESSORIES<i class="fa fa-angle-double-right"></i></a>
</li>
			</ul>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-print" title="<?php echo __("Printers") ?>" target="_self" href="#"><span class="title"><?php echo __("Printers") ?></span></a><div class="mp-level"><h2 class="fa fa-print"><?php echo __("Printers") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<h5>Printer Categories</h5>
	<div class="grid-five-col space-3">
		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Reliable</a>
</li>
							<li><a href="#">High-speed</a>
</li>
							<li><a href="#">Cost effective</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span>
						<a href="#">Small Office Printers</a>
					</span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Reliable</a>
</li>
							<li><a href="#">High-speed</a>
</li>
							<li><a href="#">Cost effective</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span>
						<a href="#">Photo All-in-One Inkjet Printers</a>
					</span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Reliable</a>
</li>
							<li><a href="#">High-speed</a>
</li>
							<li><a href="#">Cost effective</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span>
						<a href="#">Office All-in-One Inkjet Printers</a>
					</span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Crisps colors</a>
</li>
							<li><a href="#">Image quality</a>
</li>
							<li><a href="#">Very Versatile</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span>
						<a href="#">High-End Photo Printers</a>
					</span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Crisps colors</a>
</li>
							<li><a href="#">Image quality</a>
</li>
							<li><a href="#">Very Versatile</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span>
						<a href="#">Professional Printers</a>
					</span>
				</footer>
			
</div>

		
</div>

	
</div>

	<div class="grid-five-col space-3">
		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Portable</a>
</li>
							<li><a href="#">Brilliant colors</a>
</li>
							<li><a href="#">Lasting photos</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span>
						<a href="#">Compact Photo Printers</a>
					</span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">DIY projects</a>
</li>
							<li><a href="#">Home decors</a>
</li>
							<li><a href="#">Scrapbooking</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span><a href="#">Crafts & Arts Printers</a></span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">High - yield</a>
</li>
							<li><a href="#">Blazing speeds</a>
</li>
							<li><a href="#">Low energy costs</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span><a href="#">High - End Laser Printers</a></span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">Precision</a>
</li>
							<li><a href="#">Dual extruder</a>
</li>
							<li><a href="#">Optimized Build</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span><a href="#">High Quality 3D Printers</a></span>
				</footer>
			
</div>

		
</div>

		<div>
			<div class="panels container-oh">
				<div class="container-img">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/printer.jpg" class="w-100 am-scale">
					<div class="slideDown-caption a-center">
						<ul class="small-list">
							<li><a href="#">High Quality</a>
</li>
							<li><a href="#">Value for money</a>
</li>
							<li><a href="#">Discounted prices</a>
</li>
							<li class="space-t1"><a href="#">View All</a>
</li>
						</ul>

					
</div>

				
</div>

				<footer>
					<span><a href="#">Clearance Sale Printers</a></span>
				</footer>
			
</div>

		
</div>

	
</div>

	<h5>Recommended Printers</h5>
	<div class="mb-row">
		<div  class="grid-column4">
			<ul class="category-list">
				<li><a href="#">MF8580CDW (Canon)</a>
</li>
				<li><a href="#">LaserJet Pro 400 (HP)</a>
</li>
				<li><a href="#">MFC-J450DW (Brother)</a>
</li>
			</ul>

		
</div>

		<div  class="grid-column4">
			<ul class="category-list">
				<li><a href="#">OfficeJet 7110 (HP)</a>
</li>
				<li><a href="#">WorkForce M200 (Epson)</a>
</li>
				<li><a href="#">PIXMA iP2820 (Canon)</a>
</li>
			</ul>

		
</div>

		<div>
			<ul class="category-list">
				<li><a href="#">Envy 4500 (HP)</a>
</li>
				<li><a href="#">3D-FFGCREX (FlashForge)</a>
</li>
				<li><a href="#">H480 3D Printer (AFINA)</a>
</li>
			</ul>

		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-wifi" title="<?php echo __("Networking") ?>" target="_self" href="#"><span class="title"><?php echo __("Networking") ?></span></a><div class="mp-level"><h2 class="fa fa-wifi"><?php echo __("Networking") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="lg-row">
		<div  class="grid-column6">
			<h5>Networking Categories</h5>
			<div class="mb-row">
				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Wireless Routers</a>
</li>
						<li><a href="#">Wireless Adapters</a>
</li>
						<li><a href="#">Range Extenders</a>
</li>
						<li><a href="#">Adapters & Kits</a>
</li>
						<li><a href="#">Network Bluetooth</a>
</li>
						<li><a href="#">Switches</a>
</li>
						<li><a href="#">Firewalls</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Access Points</a>
</li>
						<li><a href="#">Gateways/Modems</a>
</li>
						<li><a href="#">Wireless Accessories</a>
</li>
						<li><a href="#">NAS</a>
</li>
						<li><a href="#">VoIP</a>
</li>
						<li><a href="#">IP Cameras</a>
</li>
						<li><a href="#">Monitoring Kits</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

		<div  class="grid-column6">
			<h5>Popular Brands</h5>
			<div class="mb-row">
				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">NetGear</a>
</li>
						<li><a href="#">ASUS</a>
</li>
						<li><a href="#">LinkSys</a>
</li>
						<li><a href="#">TP-Link</a>
</li>
						<li><a href="#">TrendNet</a>
</li>
						<li><a href="#">D-Link</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

				<div  class="grid-column6">
					<ul class="category-list">
						<li><a href="#">Cisco</a>
</li>
						<li><a href="#">Ruckus</a>
</li>
						<li><a href="#">Cisco</a>
</li>
						<li><a href="#">Huawei</a>
</li>
						<li><a href="#">ZyXEL</a>
</li>
						<li><a href="#" class="read-more">View All</a>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

	
</div>

	<h5>Featured Networking Items</h5>
	<div class="grid-five-col space-3">
		<div>
			<div class="container-ov overlay-icon">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/router.jpg">
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-google-plus"></a>
				<a href="#" class="fa fa-pinterest"></a>
			
</div>

			<h6 class="a-center">TP-LINK TL-PA4010KIT AV500 Dual Band Gigabit Router</h6>
			<em class="a-center d-block space-t2">
				<a href="#" class="small-font read-more">FULL SPECS <i class="fa fa-caret-right"></i></a>
			</em>
		
</div>

		<div>
			<div class="container-ov overlay-icon">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/router.jpg">
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-google-plus"></a>
				<a href="#" class="fa fa-pinterest"></a>
			
</div>

			<h6 class="a-center">ASUS RT-AC68U Wireless-AC1900 Dual Band Gigabit Router</h6>
			<em class="a-center d-block space-t2">
				<a href="#" class="small-font read-more">FULL SPECS <i class="fa fa-caret-right"></i></a>
			</em>
		
</div>

		<div>
			<div class="container-ov overlay-icon">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/router.jpg">
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-google-plus"></a>
				<a href="#" class="fa fa-pinterest"></a>
			
</div>

			<h6 class="a-center">Linksys E8350 AC2400 4X4 Dual-Band Gigabit Wi-Fi Router</h6>
			<em class="a-center d-block space-t2">
				<a href="#" class="small-font read-more">FULL SPECS <i class="fa fa-caret-right"></i></a>
			</em>
		
</div>

		<div>
			<div class="container-ov overlay-icon">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/router.jpg">
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-google-plus"></a>
				<a href="#" class="fa fa-pinterest"></a>
			
</div>

			<h6 class="a-center">NETGEAR R8000-100NAS Nighthawk Wireless Router</h6>
			<em class="a-center d-block space-t2">
				<a href="#" class="small-font read-more">FULL SPECS <i class="fa fa-caret-right"></i></a>
			</em>
		
</div>

		<div>
			<div class="container-ov overlay-icon">
				<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/router.jpg">
				<a href="#" class="fa fa-facebook"></a>
				<a href="#" class="fa fa-twitter"></a>
				<a href="#" class="fa fa-google-plus"></a>
				<a href="#" class="fa fa-pinterest"></a>
			
</div>

			<h6 class="a-center">Netgear GS108-400NAS Blackhawk GS108 Wireless Router</h6>
			<em class="a-center d-block space-t2">
				<a href="#" class="small-font read-more">FULL SPECS <i class="fa fa-caret-right"></i></a>
			</em>
		
</div>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-clock-o" title="<?php echo __("Watches") ?>" target="_self" href="#"><span class="title"><?php echo __("Watches") ?></span></a><div class="mp-level"><h2 class="fa fa-clock-o"><?php echo __("Watches") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><div class="side-colum">
	<div class="mb-row">
		<div  class="grid-column4">
			<h5>Manufacturers</h5>
			<ul class="category-list">
				<li><a href="#">ExcelVan International, Inc.</a>
</li>
				<li><a href="#">Floureon</a>
</li>
				<li><a href="#">Garmin</a>
</li>
				<li><a href="#">inDigi-USA</a>
</li>
				<li><a href="#">SAMSUNG</a>
</li>
				<li><a href="#">Garmin</a>
</li>
				<li><a href="#">PAPAGO</a>
</li>
				<li><a href="#">New Balance</a>
</li>
				<li><a href="#" class="read-more">View All</a>
</li>
			</ul>

		
</div>

		<div  class="grid-column8">
			<h5>Featured Watch</h5>
			<div>
				<div class="container-ov overlay-icon w-30">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/watch1.jpg">
					<a href="#" class="fa fa-facebook"></a>
					<a href="#" class="fa fa-twitter"></a>
					<a href="#" class="fa fa-google-plus"></a>
					<a href="#" class="fa fa-pinterest"></a>
				
</div>

				<h6>Samsung Gear Fit Wearable</h6>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, amet nulla illo iusto earum reprehenderit et porro iure quibusdam obcaecati assumenda ut quas deleniti. Consectetur, provident unde perspiciatis delectus quae. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, amet nulla illo iusto earum reprehenderit et porro iure quibusdam obcaecati assumenda ut quas deleniti. Consectetur, provident... 
					<em>
						<a href="#" class="read-more-paragraph">Read more <i class="fa fa-caret-right"></i></a>
					</em>
				</p>
			
</div>

		
</div>

	
</div>

	<div class="mb-row">
		<div  class="grid-column8">
			<h5>Smart Watch Reviews</h5>
			<div class="sub-row space-t2 a-center">
				<div  class="grid-column4">
					<div class="container-ov overlay-icon w-100">
						<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/watch2.jpg">
						<a href="#" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="#" class="fa fa-google-plus"></a>
						<a href="#" class="fa fa-pinterest"></a>
					
</div>

					<h6>Withings 70011801 Pulse Wireless</h6>
					<em>
						<a href="#" class="small-font read-more space-t2">FULL REVIEW <i class="fa fa-caret-right fa-fw"></i></a>
					</em>
				
</div>

				<div  class="grid-column4">
					<div class="container-ov overlay-icon w-100">
						<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/watch2.jpg">
						<a href="#" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="#" class="fa fa-google-plus"></a>
						<a href="#" class="fa fa-pinterest"></a>
					
</div>

					<h6>New Balance Nx990 GPS Cardio</h6>
					<em>
						<a href="#" class="small-font read-more space-t2">FULL REVIEW <i class="fa fa-caret-right fa-fw"></i></a>
					</em>
				
</div>

				<div  class="grid-column4">
					<div class="container-ov overlay-icon w-100">
						<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/watch2.jpg">
						<a href="#" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="#" class="fa fa-google-plus"></a>
						<a href="#" class="fa fa-pinterest"></a>
					
</div>

					<h6>Martian G2G X25 Smart Watch</h6>
					<em>
						<a href="#" class="small-font read-more space-t2">FULL REVIEW <i class="fa fa-caret-right fa-fw"></i></a>
					</em>
				
</div>

			
</div>

		
</div>

		<div  class="grid-column4">
			<h5>New Releases</h5>
			<ul class="category-list">
				<li><a href="#">Samsung Gear Fit Wearable</a>
</li>
				<li><a href="#">Withings 70011801 Pulse Wireless</a>
</li>
				<li><a href="#">Sony SmartWatch Bluetooth</a>
</li>
				<li><a href="#">Samsung Galaxy Gear SmartWatch</a>
</li>
				<li><a href="#">Martian G2G</a>
</li>
				<li><a href="#">Martian Victory SmartWatch</a>
</li>
				<li><a href="#">New Balance Nx990 Gps Cardio</a>
</li>
				<li><a href="#" class="read-more">View All</a>
</li>
			</ul>

		
</div>

	
</div>
																																																																																																	

</div>

</div>

</li></ul>

</div>

</li>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("About") ?>" target="_self" href="#"><span class="title"><?php echo __("About") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("About") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-history" title="<?php echo __("History") ?>" target="_self" href="#"><span class="title"><?php echo __("History") ?></span></a>
</li><li><a class="fa fa-globe" title="<?php echo __("Mission") ?>" target="_self" href="#"><span class="title"><?php echo __("Mission") ?></span></a>
</li><li><a class="fa fa-fast-forward" title="<?php echo __("Vision") ?>" target="_self" href="#"><span class="title"><?php echo __("Vision") ?></span></a>
</li><li><a class="fa fa-users" title="<?php echo __("Clients") ?>" target="_self" href="#"><span class="title"><?php echo __("Clients") ?></span></a>
</li><li><a class="fa fa-comment" title="<?php echo __("Testimonials") ?>" target="_self" href="#"><span class="title"><?php echo __("Testimonials") ?></span></a>
</li><li><a class="fa fa-question" title="<?php echo __("FAQs") ?>" target="_self" href="#"><span class="title"><?php echo __("FAQs") ?></span></a>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Services") ?>" target="_self" href="#"><span class="title"><?php echo __("Services") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Services") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-phone-square" title="<?php echo __("Technical Support") ?>" target="_self" href="#"><span class="title"><?php echo __("Technical Support") ?></span></a>
</li><li><a class="fa fa-shopping-cart" title="<?php echo __("Order Tracker") ?>" target="_self" href="#"><span class="title"><?php echo __("Order Tracker") ?></span></a>
</li><li><a class="fa fa-certificate" title="<?php echo __("Trade-In Program") ?>" target="_self" href="#"><span class="title"><?php echo __("Trade-In Program") ?></span></a>
</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-buysellads" title="<?php echo __("Advertise with us") ?>" target="_self" href="#"><span class="title"><?php echo __("Advertise with us") ?></span></a><div class="mp-level"><h2 class="fa fa-buysellads"><?php echo __("Advertise with us") ?></h2><a class="mp-back" href="#">back</a><ul><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-arrow-circle-right" title="<?php echo __("Adwords") ?>" target="_self" href="#"><span class="title"><?php echo __("Adwords") ?></span></a><div class="mp-level"><h2 class="fa fa-arrow-circle-right"><?php echo __("Adwords") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-play-circle-o" title="<?php echo __("Text") ?>" target="_self" href="#"><span class="title"><?php echo __("Text") ?></span></a>
</li><li><a class="fa fa-play-circle-o" title="<?php echo __("Ad Extensions") ?>" target="_self" href="#"><span class="title"><?php echo __("Ad Extensions") ?></span></a>
</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-play-circle-o" title="<?php echo __("Images") ?>" target="_self" href="#"><span class="title"><?php echo __("Images") ?></span></a><div class="mp-level"><h2 class="fa fa-play-circle-o"><?php echo __("Images") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-angle-double-right" title="<?php echo __("Full Width") ?>" target="_self" href="#"><span class="title"><?php echo __("Full Width") ?></span></a>
</li><li><a class="fa fa-angle-double-right" title="<?php echo __("Medium Width") ?>" target="_self" href="#"><span class="title"><?php echo __("Medium Width") ?></span></a>
</li></ul>

</div>

</li></ul>

</div>

</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Banner Ads") ?>" target="_self" href="#"><span class="title"><?php echo __("Banner Ads") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Flash Ads") ?>" target="_self" href="#"><span class="title"><?php echo __("Flash Ads") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Mobile Ads") ?>" target="_self" href="#"><span class="title"><?php echo __("Mobile Ads") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Video Ads") ?>" target="_self" href="#"><span class="title"><?php echo __("Video Ads") ?></span></a>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-money" title="<?php echo __("Affiliate") ?>" target="_self" href="#"><span class="title"><?php echo __("Affiliate") ?></span></a><div class="mp-level"><h2 class="fa fa-money"><?php echo __("Affiliate") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Pay Per Click") ?>" target="_self" href="#"><span class="title"><?php echo __("Pay Per Click") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Pay Per Performance") ?>" target="_self" href="#"><span class="title"><?php echo __("Pay Per Performance") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Pay Per Sale") ?>" target="_self" href="#"><span class="title"><?php echo __("Pay Per Sale") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Pay Per Lead") ?>" target="_self" href="#"><span class="title"><?php echo __("Pay Per Lead") ?></span></a>
</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-arrow-circle-right" title="<?php echo __("Pay Per Tier") ?>" target="_self" href="#"><span class="title"><?php echo __("Pay Per Tier") ?></span></a><div class="mp-level"><h2 class="fa fa-arrow-circle-right"><?php echo __("Pay Per Tier") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-play-circle-o" title="<?php echo __("First Tier") ?>" target="_self" href="#"><span class="title"><?php echo __("First Tier") ?></span></a>
</li><li><a class="fa fa-play-circle-o" title="<?php echo __("Second Tier") ?>" target="_self" href="#"><span class="title"><?php echo __("Second Tier") ?></span></a>
</li><li><a class="fa fa-play-circle-o" title="<?php echo __("Third Tier") ?>" target="_self" href="#"><span class="title"><?php echo __("Third Tier") ?></span></a>
</li><li><a class="fa fa-play-circle-o" title="<?php echo __("Fourth Tier") ?>" target="_self" href="#"><span class="title"><?php echo __("Fourth Tier") ?></span></a>
</li><li><a class="fa fa-play-circle-o" title="<?php echo __("Fifth Tier") ?>" target="_self" href="#"><span class="title"><?php echo __("Fifth Tier") ?></span></a>
</li></ul>

</div>

</li></ul>

</div>

</li><li><a class="fa fa-gift" title="<?php echo __("Rewards") ?>" target="_self" href="#"><span class="title"><?php echo __("Rewards") ?></span></a>
</li><li><a class="fa fa-credit-card" title="<?php echo __("Gift Cards") ?>" target="_self" href="#"><span class="title"><?php echo __("Gift Cards") ?></span></a>
</li><li><a class="fa fa-life-saver" title="<?php echo __("Rebates") ?>" target="_self" href="#"><span class="title"><?php echo __("Rebates") ?></span></a>
</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-mobile-phone" title="<?php echo __("Mobile Apps") ?>" target="_self" href="#"><span class="title"><?php echo __("Mobile Apps") ?></span></a><div class="mp-level"><h2 class="fa fa-mobile-phone"><?php echo __("Mobile Apps") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Android") ?>" target="_self" href="#"><span class="title"><?php echo __("Android") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("iOS") ?>" target="_self" href="#"><span class="title"><?php echo __("iOS") ?></span></a>
</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Windows") ?>" target="_self" href="#"><span class="title"><?php echo __("Windows") ?></span></a>
</li></ul>

</div>

</li><li><a class="fa fa-arrow-circle-right" title="<?php echo __("Store Locator") ?>" target="_self" href="#"><span class="title"><?php echo __("Store Locator") ?></span></a>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Partners") ?>" target="_self" href="#"><span class="title"><?php echo __("Partners") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Partners") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-link" title="<?php echo __("A4Tech") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("A4Tech") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __(" Acer") ?>" target="_self" href="#"><span class="title"><?php echo __(" Acer") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Adobe") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Adobe") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("AMD") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("AMD") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("AOC Monitors") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("AOC Monitors") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Apple, Inc.") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Apple, Inc.") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __(" AsusTek Computer") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __(" AsusTek Computer") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("AutoDesk") ?>" target="_self" href="#"><span class="title"><?php echo __("AutoDesk") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Canon") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Canon") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Creative Labs") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Creative Labs") ?></span></a>
</li>
</li><li><a class="fa fa-link" title="<?php echo __("Dell USA") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Dell USA") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("D-Link") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("D-Link") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Epson") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Epson") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Hewlett - Packard") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Hewlett - Packard") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("HTC") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("HTC") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Huawei") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Huawei") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("InFocus") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("InFocus") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Intel") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Intel") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("LinkSys") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("LinkSys") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Maxtor") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Maxtor") ?></span></a>
</li>
</li><li><a class="fa fa-link" title="<?php echo __("Microsoft") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Microsoft") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Motorola") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Motorola") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("NEC") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("NEC") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("NetGear") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("NetGear") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Nikon") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Nikon") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("NVIDIA") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("NVIDIA") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Olympus") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Olympus") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Panasonic") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Panasonic") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Pentax") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Pentax") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Ricoh") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Ricoh") ?></span></a>
</li>
</li><li><a class="fa fa-link" title="<?php echo __("Samsung") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Samsung") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Seagate") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Seagate") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Sony America") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Sony America") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Tiger Electronics") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Tiger Electronics") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Toshiba") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Toshiba") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("TP-Link") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("TP-Link") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("TrendNet") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("TrendNet") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("ViewSonic") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("ViewSonic") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Western Digital") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Western Digital") ?></span></a>
</li><li><a class="fa fa-link" title="<?php echo __("Xiaomi") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Xiaomi") ?></span></a>
</li>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Best Deals") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Best Deals") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Best Deals") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block gallery-layout '><div class="lg-row">
	<div class="grid-column8">
		<h5>Best Deals of the Week</h5>
		<div class="sub-row">
			<div class="grid-column4">
				<div class="a-center">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/lifechat.jpg">
					<h6>LifeChat LX-3000</h6>
					<ul class="price space-t2">
						<li class="old">Before <span>$99.99</span>
</li>
						<li class="special">Now $59.99
</li>
						<li><em><a href="#">Full specs <i class="fa fa-caret-right"></i></a></em>
</li>
					</ul>

				
</div>

			
</div>

			<div class="grid-column4">
				<div class="a-center">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/soundstation.jpg">
					<h6>SoundStation 2</h6>
					<ul class="price space-t2">
						<li class="old">Before <span>$99.99</span>
</li>
						<li class="special">Now $59.99
</li>
						<li><em><a href="#">Full specs<i class="fa fa-caret-right"></i></a></em>
</li>
					</ul>

				
</div>

			
</div>

			<div class="grid-column4">
				<div class="a-center">
					<img src="http://projects.magetop.com/projects/hanh/mcp2017/pub/media/mcpDemo/lifechat.jpg">
					<h6>Logitech Clear Chat</h6>
					<ul class="price space-t2">
						<li class="old">Before <span>$99.99</span>
</li>
						<li class="special">Now $59.99
</li>
						<li><em><a href="#">Full specs <i class="fa fa-caret-right"></i></a></em>
</li>
					</ul>

				
</div>

			
</div>

		
</div>

	
</div>

	<div class="grid-column4">
		<h5>Top Discounted Items</h5>
		<ul class="small-list num-bullet">
			<li><a href="#">Xperia C3</a>
</li>
			<li><a href="#">Asus MemoPad 8</a>
</li>
			<li><a href="#">Toshiba Chromebook 2</a>
</li>
			<li><a href="#">Lenovo ThinkPad X130e</a>
</li>
			<li><a href="#">Olympus E-M5</a>
</li>
			<li><a href="#">PlayStation 3</a>
</li>
			<li><a href="#">Acer X1170 Projector</a>
</li>
			<li><a href="#">Panasonic GM5</a>
</li>
			<li><a href="#">Rapoo V900 Mouse</a>
</li>
			<li><a href="#">HP Office 7110</a>
</li>
		</ul>

		<em><a href="#" class="btn btn-small">More items <i class="fa fa-caret-right"></i></a></em>
	
</div>
						

</div>

<div class="lg-row">
	<div class="grid-column8">
		<h5>Best Values</h5>
		<div class="sub-row">
			<div class="grid-column4">
				<ul class="small-list">
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Phones</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Tablets</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Desktops</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Laptops</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Netbooks</a>
</li>
				</ul>

			
</div>

			<div class="grid-column4">
				<ul class="small-list">
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Projectors</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Cameras</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Consoles</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Hardware</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Software</a>
</li>
				</ul>

			
</div>

			<div class="grid-column4">
				<ul class="small-list">
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Peripherals</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Accessories</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Printers</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Networking</a>
</li>
					<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Watches</a>
</li>
				</ul>

			
</div>

		
</div>

		<em><a href="#" class="btn btn-small">View all best deals  <i class="fa fa-caret-right"></i></a></em>
	
</div>

	<div class="grid-column4">
		<h5>More Ways to Save</h5>
		<ul class="small-list">
			<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Coupons</a>
</li>
			<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Gift Cards</a>
</li>
			<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Promos</a>
</li>
			<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Rebates</a>
</li>
			<li><a href="#"><i class="fa fa-chevron-circle-right"></i> Rewards</a>
</li>
		</ul>

	
</div>


</div>

</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Social") ?>" target="_self" href="#"><span class="title"><?php echo __("Social") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Social") ?></h2><a class="mp-back" href="#">back</a><ul><li><a class="fa fa-dribbble" title="<?php echo __("Dribble") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Dribble") ?></span></a>
</li><li><a class="fa fa-facebook-official" title="<?php echo __("Facebook") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Facebook") ?></span></a>
</li><li><a class="fa fa-flickr" title="<?php echo __("Flickr") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Flickr") ?></span></a>
</li><li><a class="fa fa-google-plus-square" title="<?php echo __("Google+") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Google+") ?></span></a>
</li><li><a class="fa fa-linkedin-square" title="<?php echo __("LinkedIn") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("LinkedIn") ?></span></a>
</li><li><a class="fa fa-instagram" title="<?php echo __("Instagram") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Instagram") ?></span></a>
</li>
</li><li><a class="fa fa-pinterest" title="<?php echo __("Pinterest") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Pinterest") ?></span></a>
</li><li><a class="fa fa-stumbleupon" title="<?php echo __("StumbleUpon") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("StumbleUpon") ?></span></a>
</li><li><a class="fa fa-tumblr-square" title="<?php echo __("Tumblr") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Tumblr") ?></span></a>
</li><li><a class="fa fa-twitter-square" title="<?php echo __("Twitter") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Twitter") ?></span></a>
</li><li><a class="fa fa-vine" title="<?php echo __("Vine") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Vine") ?></span></a>
</li><li><a class="fa fa-vimeo-square" title="<?php echo __("Vimeo") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Vimeo") ?></span></a>
</li>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Brands") ?>" target="_self" href="#"><span class="title"><?php echo __("Brands") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Brands") ?></h2><a class="mp-back" href="#">back</a><ul><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-star" title="<?php echo __("Top Rated Brands") ?>" target="_self" href="#"><span class="title"><?php echo __("Top Rated Brands") ?></span></a><div class="mp-level"><h2 class="fa fa-star"><?php echo __("Top Rated Brands") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block tab-content '><div class="bordered-5 space-3">
	<h3>1. Apple</h3>
	<p class="lg-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, excepturi, deserunt pariatur id repellendus repudiandae tenetur! Ea, ad ipsum laudantium rem hic non a accusantium perferendis numquam saepe deserunt placeat!</p>

</div>

<div class="bordered-3 space-2">
	<div class="lg-row">
		<div class="grid-column6">
			<h4>2. Microsoft</h4>
			<p class="md-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, hic, veritatis nihil tempore dolor excepturi sint esse a tempora iusto enim maxime amet assumenda ut natus maiores saepe adipisci nostrum.</p>
		
</div>

		<div class="grid-column6">
			<h4>3. Samsung</h4>
			<p class="md-font">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, hic, veritatis nihil tempore dolor excepturi sint esse a tempora iusto enim maxime amet assumenda ut natus maiores saepe adipisci nostrum.</p>
		
</div>

	
</div>


</div>

<div class="mb-row">
	<div class="grid-column4">
		<h5>4. Intel</h5>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, voluptate, quam minima obcaecati labore perferendis accusamus ab animi sequi at quo inventore ipsam sint eius aut quia dolor praesentium maxime.</p>
	
</div>

	<div class="grid-column4">
		<h5>5. Cisco</h5>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, voluptate, quam minima obcaecati labore perferendis accusamus ab animi sequi at quo inventore ipsam sint eius aut quia dolor praesentium maxime.</p>
	
</div>

	<div class="grid-column4">
		<h5>6. Dell, Inc.</h5>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, voluptate, quam minima obcaecati labore perferendis accusamus ab animi sequi at quo inventore ipsam sint eius aut quia dolor praesentium maxime.</p>
	
</div>


</div>

<h3 class="hint item-pos-a">
	<i class="fa fa-star fa-lg"></i>
</h3>
</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-heart" title="<?php echo __("Popular Brands") ?>" target="_self" href="#"><span class="title"><?php echo __("Popular Brands") ?></span></a><div class="mp-level"><h2 class="fa fa-heart"><?php echo __("Popular Brands") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block tab-content '><div class="mb-row space-2">
	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 1
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 2
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 3
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 4
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>


</div>

<div class="mb-row space-2">
	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 5
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 6/li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 7
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<ul class="table-list">
			<li>Brand 8
</li>
			<li>Data 1
</li>
			<li>Data 2
</li>
			<li>Data 3
</li>
			<li>Data 4
</li>
		</ul>

	
</div>


</div>

<h3 class="hint item-pos-a">
	<i class="fa fa-heart fa-lg"></i>
</h3>
</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-bookmark" title="<?php echo __("Featured Brands") ?>" target="_self" href="#"><span class="title"><?php echo __("Featured Brands") ?></span></a><div class="mp-level"><h2 class="fa fa-bookmark"><?php echo __("Featured Brands") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block tab-content '><div class="lg-row space-2">
	<div class="grid-column6">
		<h4>Logitech</h4>
		<p><img src="https://0.s3.envato.com/files/74140572/logo_001.jpg" class="l-floated-image l-float-left w-40"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio sit minima, exercitationem illo consectetur, voluptates eveniet eaque, molestias cupiditate vel placeat quos perspiciatis qui libero corporis quis quidem animi tenetur.</p>
	
</div>

	<div class="grid-column6">	
		<h4>Seagate</h4>
		<p><img src="https://0.s3.envato.com/files/74140572/logo_001.jpg" class="l-floated-image l-float-left w-40"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio sit minima, exercitationem illo consectetur, voluptates eveniet eaque, molestias cupiditate vel placeat quos perspiciatis qui libero corporis quis quidem animi tenetur.</p>
	
</div>


</div>

<div class="lg-row">	
	<div class="grid-column6">
		<div class="bordered-t1">
			<h4 class="space-t3">ViewSonic</h4>
			<p><img src="https://0.s3.envato.com/files/74140572/logo_001.jpg" class="l-floated-image l-float-left w-40"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio sit minima, exercitationem illo consectetur, voluptates eveniet eaque, molestias cupiditate vel placeat quos perspiciatis qui libero corporis quis quidem animi tenetur.</p>
		
</div>

	
</div>

	<div class="grid-column6">
		<div class="bordered-t1">
			<h4 class="space-t3">Western Digital</h4>
			<p><img src="https://0.s3.envato.com/files/74140572/logo_001.jpg" class="l-floated-image l-float-left w-40"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio sit minima, exercitationem illo consectetur, voluptates eveniet eaque, molestias cupiditate vel placeat quos perspiciatis qui libero corporis quis quidem animi tenetur.</p>
		
</div>

	
</div>


</div>

<h3 class="hint item-pos-a">
	<i class="fa fa-bookmark fa-lg"></i>
</h3>
</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="fa fa-trophy" title="<?php echo __("Top Selling Brands") ?>" target="_self" href="#"><span class="title"><?php echo __("Top Selling Brands") ?></span></a><div class="mp-level"><h2 class="fa fa-trophy"><?php echo __("Top Selling Brands") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block tab-content '><div class="mb-row space-2">
	<div class="grid-column3">
		<h4>List 1</h4>
		<ul class="small-list">
			<li><a href="#">Acer</a>
</li>
			<li><a href="#">Acronis</a>
</li>
			<li><a href="#">Adobe</a>
</li>
			<li><a href="#">AMD</a>
</li>
			<li><strong><a href="#">Apple</a></strong>
</li>
			<li><a href="#">Asus</a>
</li>
			<li><a href="#">Autodesk</a>
</li>
			<li><a href="#">Avaya</a>
</li>
			<li><a href="#">BlackBerry</a>
</li>
			<li><a href="#">Brocade</a>
</li>
			<li><a href="#">Brother</a>
</li>
			<li><a href="#">Canon</a>
</li>
			<li><a href="#">Cisco</a>
</li>
			<li><a href="#">Citrix</a>
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<h4>List 2</h4>
		<ul class="small-list">
			<li><a href="#">D-Link</a>
</li>
			<li><a href="#">Fujitsu</a>
</li>
			<li><a href="#">Google</a>
</li>
			<li><a href="#">Griffin</a>
</li>
			<li><a href="#">HP</a>
</li>
			<li><a href="#">IBM</a>
</li>
			<li><a href="#">InFocus</a>
</li>
			<li><a href="#">Intel</a>
</li>
			<li><a href="#">Juniper Networks</a>
</li>
			<li><a href="#">Kaspersky</a>
</li>
			<li><a href="#">Kingston</a>
</li>
			<li><a href="#">Kodak</a>
</li>
			<li><a href="#">LANDesk</a>
</li>
			<li><a href="#">Lenovo</a>
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<h4>List 3</h4>
		<ul class="small-list">
			<li><a href="#">Lexmark</a>
</li>
			<li><a href="#">LG</a>
</li>
			<li><a href="#">Logitech</a>
</li>
			<li><a href="#">McAfee</a>
</li>
			<li><strong><a href="#">Microsoft</a></strong>
</li>
			<li><a href="#">Motorola Solutions</a>
</li>
			<li><a href="#">NEC</a>
</li>
			<li><a href="#">NETGEAR</a>
</li>
			<li><a href="#">Novell</a>
</li>
			<li><a href="#">Oracle</a>
</li>
			<li><a href="#">Panasonic</a>
</li>
			<li><a href="#">Red Hat</a>
</li>
			<li><a href="#">Ricoh</a>
</li>
			<li><a href="#">Samsung</a>
</li>
		</ul>

	
</div>

	<div class="grid-column3">
		<h4>List 4</h4>
		<ul class="small-list">
			<li><a href="#">SAP</a>
</li>
			<li><a href="#">Seagate</a>
</li>
			<li><a href="#">ShoreTel</a>
</li>
			<li><a href="#">Sony</a>
</li>
			<li><a href="#">Symantec</a>
</li>
			<li><a href="#">Targus</a>
</li>
			<li><a href="#">Toshiba</a>
</li>
			<li><a href="#">Trend Micro</a>
</li>
			<li><a href="#">VCE</a>
</li>
			<li><a href="#">ViewSonic</a>
</li>
			<li><a href="#">VMware</a>
</li>
			<li><a href="#">Western Digital</a>
</li>
			<li><a href="#">Xerox</a>
</li>
			<li><a href="#">ZyXel</a>
</li>
		</ul>

	
</div>


</div>

<h3 class="hint item-pos-a">
	<i class="fa fa-trophy fa-lg"></i>
</h3>
</div>

</li></ul>

</div>

</li>
</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Blog") ?>" target="_self" href="<?php echo $this->_menuproModel->getBaseUrl() ?>#"><span><?php echo __("Blog") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Blog") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><h4 class="blog-title">iPad Air 2</h4>
<h5><i class="fa fa-pencil fa-fw"></i> Juan De la Cruz</h5>
<p class="text-indent">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, ipsam quas earum cum veniam est consequatur quia hic repudiandae repellendus dignissimos obcaecati nisi blanditiis rem magnam nemo sapiente.</p>
<blockquote class="text-indent">
	<em>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, ipsam quas earum cum veniam est consequatur quia hic. Natus nemo dolores, harum officiis, soluta nihil doloribus voluptas quae eius."</em>
</blockquote>
<em>
	<a href="#" class="btn btn-small">Read more <i class="fa fa-caret-right"></i></a>
</em>
<hr>
<h4 class="blog-title">Blog Title</h4>
<h5><i class="fa fa-pencil"></i> Blog Author</h5>
<p class="text-indent">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, ipsam quas earum cum veniam est consequatur quia temporibus iusto hic.</p>
<p>
	<span class="dark-note-left">
	<em>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni alias porro sunt at eveniet.</em>
	</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita, corporis, blanditiis, dicta porro voluptate quis aliquid cupiditate beatae placeat nobis neque reiciendis nisi temporibus iusto voluptatum aut tempora modi voluptatibus. Nihil, in sunt fuga iure iusto amet at repellat vitae. Ipsam, ab, atque neque adipisci repellendus nam rem odio quam recusandae nesciunt laceat nobis temporibus iusto sneque reiciendis.
</p>
<em><a href="#" class="btn btn-small">Read more <i class="fa fa-caret-right"></i></a></em>
</div>

</li></ul>

</div>

</li><li class="mb-icon mb-icon-arrow-left"><a class="" title="<?php echo __("Sign up") ?>" target="_self" href="#"><span class="title"><?php echo __("Sign up") ?></span></a><div class="mp-level"><h2 class=""><?php echo __("Sign up") ?></h2><a class="mp-back" href="#">back</a><ul><li><div class='static-block  '><h3 class="block-title a-center">create your account</h3>
<form action="#" method="post">
	<div class="form-group-lg">
		<label for="username"><i class="fa fa-user"></i> USERNAME</label>
		<input type="text" name="username" id="username" maxlength="20" placeholder="your username" class="linear" required>
	
</div>

	<div class="form-group-lg">
		<label for="email"><i class="fa fa-envelope-o"></i> E-MAIL ADDRESS</label>
		<input type="email" name="email" id="email" placeholder="your e-mail address" class="linear" required>
	
</div>

	<div class="form-group-lg">
		<label for="password"><i class="fa fa-lock"></i> PASSWORD</label>
		<input type="password" name="password" id="password" placeholder="your password" class="linear" required>
	
</div>

	<div class="form-group-lg">
		<label for="confirm_password"><i class="fa fa-repeat"></i> CONFIRM PASSWORD</label>
		<input type="password" name="confirm_password" id="confirm_password" placeholder="confirm password" class="linear" required>
	
</div>

	<div class="form-group-lg">
		<input type="submit" class="btn" value="Sign Up">
	
</div>

	<div class="form-group-lg">
		<p>By clicking on Sign Up above, you confirm that you accept the <a href="#" class="read-more">Terms of Use</a></p>
	
</div>

</form>
</div>

</li></ul>

</div>

</li></ul>
