<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<li class="top-currency">
	<span><?php echo $block->escapeHtml($currentCurrencyCode) ?></span>
	<div class="nav-drop-menu currency_nav">
		<ul class="switcher-currency">
			<?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
	</div>
</li>
<?php endif; ?>
