<?php
/**
 * Magetop 
 * @category    Magetop 
 * @copyright   Copyright (c) 2017 Magetop (http://magetop.com/) 
 * @Author: Hanh Nguyen<hanhkaka.nguyen37@gamil.com>
 * @@Create Date: 2013-05-5
 * @@Modify Date: 2017-06-05
 */
/*--------------------*/
$groupId = $this->getGroupmenuId ();
$responsive = 'mcp-push-cover';
$groupInfo = $block->getGroupInfo();
$MCPHTML = $MCPRHTML = "";
$MCPRHTML = $this->getPushnewResponsiveHtml($groupId, $responsive);
$MCPHTML .= '<div class="mcp_responsive">' . $MCPRHTML . '</div>';
if ($this->helper('Magetop\Menupro\Helper\Data')->isDevelopMode()) {
	$MCPHTML .= $this->getMenuHtml($groupId);
} else {
	$MCPHTML .= $this->getStaticHtml($groupId);
}	
echo "<div class='mst mcp-wrapper'>";
echo $MCPHTML;
echo "</div>";

?>